### ISSUE TITLE
Crash on Start

### ISSUE THREAD

**Issue by LobsterCorgi** [ImpactDevelopment/ImpactClient#1040]
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error

I made sure that Auto Clicker is turned to False. (Im using Impact 1.13.2)

---- Minecraft Crash Report ----
// Don't do that.

Time: 3/27/19 12:21 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at cft.c(SourceFile:827)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by ScanmanTM** [comment]
Close this, this retard didn't read for donators only.
