### ISSUE TITLE
Baritone crashes when mining leaves

### ISSUE THREAD

**Issue by ScanmanTM** [ImpactDevelopment/ImpactClient#1119]
**Describe the bug**
When you do .b mine leaves and when the bot tries to mine them your game crashes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Type .b mine oak_leaves
2. baritone will attempt to mine them
3. crash

<details> 
  <summary><strong>Game output</strong></summary>
 

```
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// There are four lights!

Time: 12/04/19 15:54
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at me.zero.clarinet.2X.onPathEvent(2X.java:40)
	at baritone.y.a(Unknown Source)
	at baritone.y$$Lambda$2591/1375798147.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.y.onPathEvent(Unknown Source)
	at baritone.j.c(Unknown Source)
	at baritone.j.onTick(Unknown Source)
	at baritone.y.a(Unknown Source)
	at baritone.y$$Lambda$2588/1201282426.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.y.onTick(Unknown Source)
	at cft.handler$runTick$zei000(SourceFile)
	at cft.m(SourceFile:1244)
	at cft.c(SourceFile:821)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 513520352 bytes (489 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.13.2-Impact_4.6
	LWJGL: 3.1.6 build 14
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 419.67, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX(tm)-8350 Eight-Core Processor 
	OptiFine Version: OptiFine_1.13.2_HD_U_E7
	OptiFine Build: 20190322-164033
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS_PTGI_E6.zip
	OpenGlVersion: 4.6.0 NVIDIA 419.67
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.6 1.13
- Using Optifine?  Yes
- Using LiteLoader?  No
- Enabled mods: 
No fall
Anti desync
Nametags
ESP
- Operating System:  W10

</details>

<sub><sub>crashitone<sub><sub>

**Comment by leijurv** [comment]
Fixed a few days ago in Baritone v1.3.1, awaiting a hotfix into impcat.
