### ISSUE TITLE
Impact 4.6 for 1.13.2 keeps crashing

### ISSUE THREAD

**Issue by TheAceKlepto** [ImpactDevelopment/ImpactClient#1121]
**Describe the bug**
I was using auto miner on a server, I made the target redstone and I got the following error:
The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Ticking entity

I deleted the impact folder but no luck. I cannot load singplayer either anymore with impact.

EDIT
I originally deleted the versions folder. When I deleted the actual Impact folder in .minecraft that seemed to fix it temporarily until I did the same thing again. 

```
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 4/12/19 12:52 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at java.util.Objects.requireNonNull(Objects.java:203)
	at baritone.p.a(Unknown Source)
	at baritone.ch$$Lambda$2782/73244884.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:576)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:255)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
	at baritone.ch.mineByName(Unknown Source)
	at baritone.api.process.IMineProcess.mineByName(Unknown Source)
	at me.zero.clarinet.3I.lambda$new$1(3I.java:10)
	at me.zero.clarinet.3I$$Lambda$1603/192030256.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$1090/999014315.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at clientapi.7.post(7.java:7)
	at ctj.handler$onPostUpdate$zzd000(SourceFile:1221)
	at ctj.R_(SourceFile:234)
	at axy.a(SourceFile:1243)
	at axy.g(SourceFile:1218)
	at axy.o_(SourceFile:1100)
	at cft.m(SourceFile:1281)
	at cft.c(SourceFile:821)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:203)
	at baritone.p.a(Unknown Source)
	at baritone.ch$$Lambda$2782/73244884.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:576)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:255)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
	at baritone.ch.mineByName(Unknown Source)
	at baritone.api.process.IMineProcess.mineByName(Unknown Source)
	at me.zero.clarinet.3I.lambda$new$1(3I.java:10)
	at me.zero.clarinet.3I$$Lambda$1603/192030256.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$1090/999014315.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at clientapi.7.post(7.java:7)
	at ctj.handler$onPostUpdate$zzd000(SourceFile:1221)
	at ctj.R_(SourceFile:234)
	at axy.a(SourceFile:1243)
	at axy.g(SourceFile:1218)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (ctj)
	Entity ID: 5485691
	Entity Name: TheAceKlepto
	Entity's Exact location: 157883.30, 45.00, 102148.21
	Entity's Block location: World: (157883,45,102148), Chunk: (at 11,2,4 in 9867,6384; contains blocks 157872,0,102144 to 157887,255,102159), Region: (308,199; contains chunks 9856,6368 to 9887,6399, blocks 157696,0,101888 to 158207,255,102399)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at axy.o_(SourceFile:1100)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [ctj['TheAceKlepto'/5485691, l='MpServer', x=157883.30, y=45.00, z=102148.21]]
	Chunk stats: MultiplayerChunkCache: 82, 82
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (64,67,-160), Chunk: (at 0,4,0 in 4,-10; contains blocks 64,0,-160 to 79,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 99439 game time, 336540234 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [ctj['TheAceKlepto'/5485691, l='MpServer', x=157883.30, y=45.00, z=102148.21]]
	Retry entities: 0 total; []
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at crg.a(SourceFile:418)
	at cft.b(SourceFile:1815)
	at cft.a(SourceFile:403)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 338671520 bytes (322 MB) / 771751936 bytes (736 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.13.2-Impact_4.6
	LWJGL: 3.1.6 build 14
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 418.81, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
```

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System:

**Comment by usereewrjrjeejr** [comment]
Make sure it's targeting lit_redstone_ore as well?

**Comment by TheAceKlepto** [comment]
> Make sure it's targeting lit_redstone_ore as well?

How would I even do that? the options are pre-set. Its under Auto-Mine, Bot , Target

**Comment by usereewrjrjeejr** [comment]
.b mine block_name

**Comment by leijurv** [comment]
Fixed for next release
