### ISSUE TITLE
impact 1.13.2 4.6 keeps crashing

### ISSUE THREAD

**Issue by KxngCartier** [ImpactDevelopment/ImpactClient#1127]
**Describe the bug**
impact 1.13.2 4.6  keeps crashing

**To Reproduce**
install impact, launch minecraft with impact
watch you game crash as soon as it finished starting up

**Expected behavior**
to load up without an instantneous crash

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```
Clear all
Filter text
3 fatals44 errors15 warnings105 infos5181 debugs
18:32:49
launcher
main
debug
Preparing crit2.ogg
18:32:49
launcher
main
debug
Local file C:\Users\joes youtube filming\AppData\Roaming\.minecraft\assets\objects\7a\7a4f2566e6d1ff536a9c6d7f9a0d804d15a3ce62 has filesize of 5225 bytes
18:32:49
launcher
main
debug
Preparing crit3.ogg
18:32:49
launcher
main
debug
Local file C:\Users\joes youtube filming\AppData\Roaming\.minecraft\assets\objects\22\2211e494688ba04b0c4658ed74d7e48c2d391c33 has filesize of 4720 bytes
18:32:49
launcher
main
debug
Got local file for place3.ogg
18:32:49
launcher
main
debug
Preparing knockback1.ogg
18:32:49
launcher
main
debug
Got local file for crit2.ogg
18:32:49
launcher
main
debug
Got local file for place4.ogg
18:32:49
launcher
main
debug
Got local file for crit1.ogg
18:32:49
launcher
main
debug
Got local file for knockback1.ogg
18:32:49
launcher
main
debug
Local file C:\Users\joes youtube filming\AppData\Roaming\.minecraft\assets\objects\f8\f82bb1724f94ef3e2cd80a0e41ed0ca54c8f7502 has filesize of 4708 bytes
18:32:49
launcher
main
debug
Local file C:\Users\joes youtube filming\AppData\Roaming\.minecraft\assets\objects\1b\1b172129daf7cd9a36d2b0f7820baf2e479e381a has filesize of 9783 bytes
18:32:49
launcher
main
debug
Local file C:\Users\joes youtube filming\AppData\Roaming\.minecraft\assets\objects\50\509656b6d02a4491f46c686e66b615950c6c1408 has filesize of 8223 bytes
18:32:49
launcher
main
debug
Local file C:\Users\joes youtube filming\AppData\Roaming\.minecraft\assets\objects\08\08d3912d571693d82692458132d4de59928f16d6 has filesize of 4920 bytes
18:32:49
launcher
main
debug
Preparing knockback3.ogg
18:32:49
launcher
main
debug
Preparing knockback2.ogg
18:32:49
launcher
main
debug
Preparing knockback4.ogg
18:32:49
launcher
main
debug
Preparing strong1.ogg
18:32:49
launcher
main
debug
Got local file for crit3.ogg
18:32:49
launcher
main
debug
Got local file for knockback3.ogg
18:32:49
launcher
main
debug
Local file C:\Users\joes youtube filming\AppData\Roaming\.minecraft\assets\objects\08\08626fc2a337c28b5dfdafb6daa9ea31f9a70571 has filesize of 8148 bytes
18:32:49
launcher
main
debug
Local file C:\Users\joes youtube filming\AppData\Roaming\.minecraft\assets\objects\15\15bbaf7901d7abff12bb872ff88a6ad541f5227a has filesize of 8273 bytes
18:32:49
launcher
main
debug
Preparing strong2.ogg
18:32:49
launcher
main
debug
Preparing strong3.ogg
18:32:49
launcher
main
debug
Got local file for strong1.ogg
18:32:49
launcher
main
debug
Got local file for knockback2.ogg
18:32:49
launcher
main
debug
Local file C:\Users\joes youtube filming\AppData\Roaming\.minecraft\assets\objects\08\085a6cd2e023877254d1118c403f39e556c003cb has filesize of 8234 bytes
18:32:49
launcher
main
debug
Got local file for knockback4.ogg
18:32:49
launcher
main
debug
Preparing strong4.ogg
18:32:49
launcher
main
debug
Got local file for strong2.ogg
18:32:49
launcher
main
debug
Local file C:\Users\joes youtube filming\AppData\Roaming\.minecraft\assets\objects\d7\d7067e204913cf9631bfbb7340102f6de75c2dfc has filesize of 5194 bytes
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 4/12/19 6:23 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at cft.c(SourceFile:827)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 356028720 bytes (339 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.13.2-Impact_4.6-beta
	LWJGL: 3.1.6 build 14
	OpenGL: AMD Radeon R9 200 Series GL version 4.5.13492 Compatibility Profile Context 22.19.677.257, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.6 for 1.13.2
- Using Optifine?  no
- Using LiteLoader?  no
- Enabled mods:  no
- Operating System:  windows 10, 64 bit

</details>

**Additional context**

**Comment by usereewrjrjeejr** [comment]
***Launched Version: 1.13.2-Impact_4.6-beta***

**Comment by ZeroMemes** [comment]
Use the official release! I explicitly said in the releases channel that the beta was only available to donators!

**Comment by usereewrjrjeejr** [comment]
Remove the download to the beta

**Comment by clerickx** [comment]
i think it might have something to do with fabric or mods

**Comment by l1ving** [comment]
Why do you keep commenting on year old issues??
