### ISSUE TITLE
File picker dialogs don't open (e.g. Alt import/export)

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#1270]
**Describe the bug**
Clicking Import or Export does nothing. This is the same underlying cause as #1151.

**To Reproduce**
1. Go to the Alt manager GUI
2. Click on Import
3. Nothing happens

**Expected behavior**
A file picker opens to choose what to import or where to export

<details> 
  <summary><strong>Game output</strong></summary>
 

```
Exception in thread "pool-7-thread-1" [20:48:47] [pool-7-thread-1/INFO]: [STDERR]: java.awt.HeadlessException
[20:48:47] [pool-7-thread-1/INFO]: [STDERR]: 	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
[20:48:47] [pool-7-thread-1/INFO]: [STDERR]: 	at java.awt.Window.init(Window.java:484)
[20:48:47] [pool-7-thread-1/INFO]: [STDERR]: 	at java.awt.Window.<init>(Window.java:436)
[20:48:47] [pool-7-thread-1/INFO]: [STDERR]: 	at java.awt.Window.<init>(Window.java:591)
[20:48:47] [pool-7-thread-1/INFO]: [STDERR]: 	at java.awt.Dialog.<init>(Dialog.java:665)
[20:48:47] [pool-7-thread-1/INFO]: [STDERR]: 	at java.awt.Dialog.<init>(Dialog.java:409)
[20:48:47] [pool-7-thread-1/INFO]: [STDERR]: 	at java.awt.FileDialog.<init>(FileDialog.java:218)
[20:48:47] [pool-7-thread-1/INFO]: [STDERR]: 	at me.zero.clarinet.manage.alt.gui.GuiAltList.lambda$null$0(GuiAltList.java:101)
[20:48:47] [pool-7-thread-1/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[20:48:47] [pool-7-thread-1/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[20:48:47] [pool-7-thread-1/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.6 (tested on latest commit)
- Minecraft version: 1.13.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: N/A

</details>

**Additional context**
Should only affect 1.13+

**Comment by Cerbiac** [comment]
Duplicate of #1151 
:kappa:
But seriously though, should we not comment on closed threads?

**Comment by LeafHacker** [comment]
This shares a cause with #1151 but has different symptoms and will require a different solution.

If it was the same issue or shared a solution then sure, it should be discussed there.

**Comment by StijnSimons** [comment]
I'd say make a custom file dialog instead of using Swing's one
