### ISSUE TITLE
Crashing while joining lobbys and games on 'gommehd.net'

### ISSUE THREAD

**Issue by AstragoYT** [ImpactDevelopment/ImpactClient#1285]
**ALL BUNGEECORD SERVERS**

**Describe the bug**
If I want to join gommehd.net lobbies (example skywars)

**To Reproduce**
1. Go to the server 'gommehd.net'
2. Click on a sign to join lobbies  (skywars...)

**Expected behavior**
joining the server

**Screenshots**
-/-

<details> 
  <summary><strong>Game output</strong></summary>
 

```


```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 11.06.19 09:24
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at bji.w(SourceFile:120)
	at me.zero.clarinet.3M.lambda$null$0(3M.java:31)
	at me.zero.clarinet.3M$$Lambda$2692/625118123.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at me.zero.clarinet.3M.lambda$null$1(3M.java:118)
	at me.zero.clarinet.3M$$Lambda$2689/957428653.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at me.zero.clarinet.3M.lambda$new$4(3M.java:100)
	at me.zero.clarinet.3M$$Lambda$1373/1594694157.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$1097/775136432.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at clientapi.7.post(7.java:7)
	at cty.handler$onStartHand$zzh000(EntityRenderer.java:2394)
	at cty.b(EntityRenderer.java:1544)
	at cty.a(EntityRenderer.java:1217)
	at cty.a(EntityRenderer.java:979)
	at cft.c(SourceFile:850)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at bji.w(SourceFile:120)
	at me.zero.clarinet.3M.lambda$null$0(3M.java:31)
	at me.zero.clarinet.3M$$Lambda$2692/625118123.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at me.zero.clarinet.3M.lambda$null$1(3M.java:118)
	at me.zero.clarinet.3M$$Lambda$2689/957428653.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at me.zero.clarinet.3M.lambda$new$4(3M.java:100)
	at me.zero.clarinet.3M$$Lambda$1373/1594694157.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$1097/775136432.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at clientapi.7.post(7.java:7)
	at cty.handler$onStartHand$zzh000(EntityRenderer.java:2394)
	at cty.b(EntityRenderer.java:1544)
	at cty.a(EntityRenderer.java:1217)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [ctj['Astrago'/2835, l='MpServer', x=0.50, y=100.00, z=0.50], ctk['GodlikeKira'/64, l='MpServer', x=41.68, y=100.81, z=-1.93]]
	Chunk stats: MultiplayerChunkCache: 165, 165
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (69,4,928), Chunk: (at 5,0,0 in 4,58; contains blocks 64,0,928 to 79,255,943), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Level time: 3662519 game time, 6000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 72 total; [alz['Rüstungsständer'/128, l='MpServer', x=66.50, y=99.00, z=-23.50], ctj['Astrago'/2835, l='MpServer', x=0.50, y=100.00, z=0.50], ctk['GodlikeKira'/64, l='MpServer', x=41.68, y=100.81, z=-1.93], ame['Gemälde'/96, l='MpServer', x=35.00, y=120.50, z=27.03], aob['Dorfbewohner'/62, l='MpServer', x=9.50, y=100.00, z=4.50], alz[''/63, l='MpServer', x=9.50, y=102.22, z=4.50], ctk['GodlikeKira'/64, l='MpServer', x=41.68, y=100.81, z=-1.93], alz['Rüstungsständer'/65, l='MpServer', x=-1.22, y=100.69, z=0.19], alz['Rüstungsständer'/66, l='MpServer', x=-1.50, y=101.00, z=0.50], alz['Rüstungsständer'/67, l='MpServer', x=7.59, y=101.28, z=-3.13], alz['Rüstungsständer'/68, l='MpServer', x=7.38, y=99.88, z=-3.50], alz['Rüstungsständer'/69, l='MpServer', x=8.19, y=101.00, z=-3.00], alz['Rüstungsständer'/70, l='MpServer', x=7.78, y=100.78, z=-2.63], alz['Rüstungsständer'/71, l='MpServer', x=30.50, y=100.97, z=9.50], alz['Rüstungsständer'/72, l='MpServer', x=26.50, y=98.59, z=11.50], alz['Rüstungsständer'/73, l='MpServer', x=23.50, y=100.00, z=15.00], alz['Rüstungsständer'/74, l='MpServer', x=30.50, y=100.97, z=4.50], alz['Rüstungsständer'/75, l='MpServer', x=30.50, y=100.97, z=6.50], ame['Gemälde'/112, l='MpServer', x=74.03, y=101.50, z=-15.00], alz['Rüstungsständer'/76, l='MpServer', x=-0.63, y=100.34, z=-5.50], alz['Rüstungsständer'/77, l='MpServer', x=22.50, y=100.38, z=16.50], ame['Gemälde'/114, l='MpServer', x=75.00, y=113.50, z=-15.97], alz['Rüstungsständer'/78, l='MpServer', x=22.50, y=100.69, z=16.50], alz['Rüstungsständer'/79, l='MpServer', x=22.50, y=99.78, z=16.50], amb['Rahmen'/80, l='MpServer', x=7.50, y=101.50, z=-25.97], amb['Rahmen'/81, l='MpServer', x=7.50, y=102.50, z=-25.97], alz['Rüstungsständer'/82, l='MpServer', x=32.50, y=101.28, z=3.50], alz['Rüstungsständer'/83, l='MpServer', x=27.50, y=104.25, z=-21.50], alz['Rüstungsständer'/84, l='MpServer', x=29.38, y=102.28, z=-20.63], alz['Rüstungsständer'/85, l='MpServer', x=31.50, y=102.28, z=-21.50], alz['Rüstungsständer'/86, l='MpServer', x=30.97, y=102.69, z=-19.50], alz['Rüstungsständer'/87, l='MpServer', x=30.78, y=102.59, z=-18.72], alz['Rüstungsständer'/88, l='MpServer', x=30.28, y=102.50, z=-19.31], alz['Rüstungsständer'/89, l='MpServer', x=31.19, y=102.38, z=-19.00], amb['Rahmen'/90, l='MpServer', x=30.50, y=103.50, z=-20.03], amb['Rahmen'/91, l='MpServer', x=31.50, y=103.50, z=-20.03], alz['Rüstungsständer'/92, l='MpServer', x=44.28, y=93.47, z=-6.63], alz['Rüstungsständer'/93, l='MpServer', x=44.00, y=93.00, z=-5.31], alz['Rüstungsständer'/94, l='MpServer', x=44.28, y=93.47, z=-6.41], alz['Rüstungsständer'/95, l='MpServer', x=40.50, y=101.00, z=-10.50], ame['Gemälde'/96, l='MpServer', x=35.00, y=120.50, z=27.03], alz['Rüstungsständer'/97, l='MpServer', x=36.19, y=118.88, z=32.50], apk['Lore'/98, l='MpServer', x=59.50, y=97.06, z=1.47], alz['Rüstungsständer'/99, l='MpServer', x=52.50, y=105.50, z=10.00], alz['Rüstungsständer'/100, l='MpServer', x=49.00, y=94.00, z=-12.91], alz['Rüstungsständer'/101, l='MpServer', x=54.50, y=104.28, z=16.47], alz['Rüstungsständer'/102, l='MpServer', x=54.50, y=103.09, z=16.47], alz['Rüstungsständer'/103, l='MpServer', x=54.50, y=103.69, z=16.47], alz['Rüstungsständer'/104, l='MpServer', x=54.50, y=104.88, z=16.47], amb['Rahmen'/105, l='MpServer', x=41.50, y=101.50, z=-34.97], amb['Rahmen'/106, l='MpServer', x=59.50, y=102.50, z=-19.97], alz['Rüstungsständer'/107, l='MpServer', x=63.50, y=104.88, z=-21.50], alz['Rüstungsständer'/108, l='MpServer', x=72.50, y=105.00, z=12.50], alz['Rüstungsständer'/109, l='MpServer', x=76.50, y=105.00, z=-14.63], alz['Rüstungsständer'/110, l='MpServer', x=76.50, y=105.88, z=-15.72], alz['Rüstungsständer'/111, l='MpServer', x=75.19, y=105.19, z=-14.50], ame['Gemälde'/112, l='MpServer', x=74.03, y=101.50, z=-15.00], alz['Rüstungsständer'/113, l='MpServer', x=64.38, y=100.00, z=-14.13], ame['Gemälde'/114, l='MpServer', x=75.00, y=113.50, z=-15.97], amb['Rahmen'/115, l='MpServer', x=67.97, y=118.50, z=28.50], alz['Rüstungsständer'/116, l='MpServer', x=67.69, y=118.47, z=28.50], amb['Rahmen'/117, l='MpServer', x=72.50, y=107.50, z=-20.03], amb['Rahmen'/118, l='MpServer', x=71.50, y=105.50, z=-20.03], amb['Rahmen'/119, l='MpServer', x=71.50, y=106.50, z=-20.03], alz['Rüstungsständer'/120, l='MpServer', x=71.50, y=99.00, z=-30.50], amb['Rahmen'/121, l='MpServer', x=72.50, y=105.50, z=-20.03], alz['Rüstungsständer'/122, l='MpServer', x=64.28, y=103.59, z=-16.31], amb['Rahmen'/123, l='MpServer', x=72.50, y=106.50, z=-20.03], alz['Rüstungsständer'/124, l='MpServer', x=73.38, y=98.50, z=-17.50], amb['Rahmen'/125, l='MpServer', x=71.50, y=107.50, z=-20.03], alz['Rüstungsständer'/126, l='MpServer', x=72.50, y=109.88, z=-24.50], alz['Rüstungsständer'/127, l='MpServer', x=77.50, y=100.00, z=-16.50]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.14-SNAPSHOT:077cf8b:unknown) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at crg.a(WorldClient.java:576)
	at cft.b(SourceFile:1815)
	at cft.a(SourceFile:408)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 400464712 bytes (381 MB) / 939524096 bytes (896 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.13.2-Impact_4.6
	LWJGL: 3.1.6 build 14
	OpenGL: GeForce RTX 2070/PCIe/SSE2 GL version 4.6.0 NVIDIA 419.17, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/FaithfulVenom-32x-1.13-r2.zip, file/1.14 Default resourcepack, file/Standart.zip
	Current Language: Deutsch (Deutschland)
	Profiler Position: N/A (disabled)
	CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**
Maybe bungee cord server

**Comment by zPeanut** [comment]
der genannte server namens gommehd.net ist ein server dessen qualität nicht gerade dem eines populären server entspricht. das serverteam ist seht inkompetent im handeln von fällen und so nicht gerade passend für einen server derartigen popularität.
thanks for coming to my tedtalk

**Comment by ZeroMemes** [comment]
Disable Storage ESP to fix this for now. This is already fixed in 4.7 and is the same issue that is addressed by #1380

**Comment by 0-x-2-2** [comment]
why stworage esp cwash 😭
