### ISSUE TITLE
Can't launch the game with Impact installed.

### ISSUE THREAD

**Issue by SRR8** [ImpactDevelopment/ImpactClient#1365]
**Describe the bug**
Whenever Impact is in my mod folder the game just refuses to launch.

**To Reproduce**
1. Install Impact 4.6
2. Click play
3. Crash.

**Expected behavior**
The game loads with Impact loaded.

[04:15:36] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[04:15:36] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[04:15:36] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[04:15:36] [main/INFO]: Forge Mod Loader version 14.23.5.2838 for Minecraft 1.12.2 loading
[04:15:36] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64
[04:15:37] [main/INFO]: Searching C:\Users\JoshS\AppData\Roaming\.minecraft\1.12 - Copy\mods for mods
[04:15:37] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-0.3.3.22.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[04:15:37] [main/WARN]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:15:37] [main/WARN]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[04:15:37] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ForgeWurst-0.11-MC1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[04:15:37] [main/WARN]: The coremod WCoreMod (net.wurstclient.forge.asm.WCoreMod) is not signed!
[04:15:37] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from Impact-4.6-1.12.2.jar
[04:15:37] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.63.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[04:15:37] [main/WARN]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:15:37] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from malisiscore-1.12.2-6.5.1.jar
[04:15:37] [main/WARN]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:15:37] [main/WARN]: The coremod MicdoodlePlugin (micdoodle8.mods.miccore.MicdoodlePlugin) is not signed!
[04:15:37] [main/WARN]: The coremod com.therandomlabs.randompatches.core.RPCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:15:37] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in redstonepaste-mc1.12-1.7.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[04:15:37] [main/WARN]: The coremod net.fybertech.nwr.NWRTweak does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:15:37] [main/WARN]: The coremod NWRTweak (net.fybertech.nwr.NWRTweak) is not signed!
[04:15:37] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from phosphor-1.12.2-0.2.4+build46.jar
[04:15:37] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[04:15:37] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[04:15:37] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/JoshS/AppData/Roaming/.minecraft/1.12%20-%20Copy/mods/Impact-4.6-1.12.2.jar Service=LaunchWrapper Env=CLIENT
[04:15:37] [main/DEBUG]: Instantiating coremod class MalisisCorePlugin
[04:15:37] [main/WARN]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:15:37] [main/WARN]: The coremod MalisisCorePlugin (net.malisis.core.asm.MalisisCorePlugin) is not signed!
[04:15:37] [main/INFO]: Compatibility level set to JAVA_8
[04:15:37] [main/DEBUG]: Enqueued coremod MalisisCorePlugin
[04:15:37] [main/DEBUG]: Instantiating coremod class PhosphorFMLLoadingPlugin
[04:15:37] [main/DEBUG]: The coremod me.jellysquid.mods.phosphor.core.PhosphorFMLLoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[04:15:37] [main/DEBUG]: Found signing certificates for coremod PhosphorFMLLoadingPlugin (me.jellysquid.mods.phosphor.core.PhosphorFMLLoadingPlugin)
[04:15:37] [main/DEBUG]: Found certificate f0387d288626cc2d937daa504e74af570c52a2f1
[04:15:37] [main/DEBUG]: Enqueued coremod PhosphorFMLLoadingPlugin
[04:15:37] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[04:15:37] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[04:15:37] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[04:15:37] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[04:15:37] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[04:15:37] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[04:15:37] [main/DEBUG]: Injecting coremod FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
[04:15:37] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[04:15:37] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[04:15:37] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[04:15:37] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
[04:15:37] [main/DEBUG]: Injection complete
[04:15:37] [main/DEBUG]: Running coremod plugin for FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
[04:15:37] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[04:15:39] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[04:15:39] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[04:15:39] [main/DEBUG]: Coremod plugin class FMLCorePlugin run successfully
[04:15:39] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[04:15:39] [main/DEBUG]: Injecting coremod FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\} class transformers
[04:15:39] [main/DEBUG]: Injection complete
[04:15:39] [main/DEBUG]: Running coremod plugin for FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\}
[04:15:39] [main/DEBUG]: Running coremod plugin FMLForgePlugin
[04:15:39] [main/DEBUG]: Coremod plugin class FMLForgePlugin run successfully
[04:15:39] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[04:15:39] [main/DEBUG]: Injecting coremod WCoreMod \{net.wurstclient.forge.asm.WCoreMod\} class transformers
[04:15:39] [main/TRACE]: Registering transformer net.wurstclient.forge.asm.WClassTransformer
[04:15:39] [main/DEBUG]: Injection complete
[04:15:39] [main/DEBUG]: Running coremod plugin for WCoreMod \{net.wurstclient.forge.asm.WCoreMod\}
[04:15:39] [main/DEBUG]: Running coremod plugin WCoreMod
[04:15:39] [main/DEBUG]: Coremod plugin class WCoreMod run successfully
[04:15:39] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[04:15:39] [main/DEBUG]: Injecting coremod MicdoodlePlugin \{micdoodle8.mods.miccore.MicdoodlePlugin\} class transformers
[04:15:39] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:99]: Successfully Registered Transformer
[04:15:39] [main/TRACE]: Registering transformer micdoodle8.mods.miccore.MicdoodleTransformer
[04:15:39] [main/DEBUG]: Injection complete
[04:15:39] [main/DEBUG]: Running coremod plugin for MicdoodlePlugin \{micdoodle8.mods.miccore.MicdoodlePlugin\}
[04:15:39] [main/DEBUG]: Running coremod plugin MicdoodlePlugin
[04:15:40] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:292]: [Micdoodle8Core]: Patching game...
[04:15:40] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:292]: [Micdoodle8Core]: Patching game...
[04:15:40] [main/DEBUG]: Coremod plugin class MicdoodlePlugin run successfully
[04:15:40] [main/INFO]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[04:15:40] [main/ERROR]: Mixin config mixins.impact.json does not specify "minVersion" property
[04:15:40] [main/ERROR]: Mixin config mixins.baritone.json does not specify "minVersion" property
[04:15:40] [main/INFO]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@6d5f4900
[04:15:40] [main/DEBUG]: Injecting coremod MalisisCorePlugin \{net.malisis.core.asm.MalisisCorePlugin\} class transformers
[04:15:40] [main/DEBUG]: Injection complete
[04:15:40] [main/DEBUG]: Running coremod plugin for MalisisCorePlugin \{net.malisis.core.asm.MalisisCorePlugin\}
[04:15:40] [main/DEBUG]: Running coremod plugin MalisisCorePlugin
[04:15:40] [main/DEBUG]: Coremod plugin class MalisisCorePlugin run successfully
[04:15:40] [main/DEBUG]: Injecting coremod PhosphorFMLLoadingPlugin \{me.jellysquid.mods.phosphor.core.PhosphorFMLLoadingPlugin\} class transformers
[04:15:40] [main/DEBUG]: Injection complete
[04:15:40] [main/DEBUG]: Running coremod plugin for PhosphorFMLLoadingPlugin \{me.jellysquid.mods.phosphor.core.PhosphorFMLLoadingPlugin\}
[04:15:40] [main/DEBUG]: Running coremod plugin PhosphorFMLLoadingPlugin
[04:15:40] [main/INFO]: Phosphor has been hooked by Forge, setting up Mixin and plugins
[04:15:40] [main/DEBUG]: Coremod plugin class PhosphorFMLLoadingPlugin run successfully
[04:15:40] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[04:15:40] [main/DEBUG]: Validating minecraft
[04:15:40] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[04:15:40] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[04:15:40] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[04:15:40] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[04:15:40] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[04:15:40] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[04:15:40] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[04:15:40] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[04:15:40] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[04:15:40] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[04:15:40] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[04:15:40] [main/INFO]: Loading configuration
[04:15:41] [main/INFO]: A re-entrant transformer '$wrapper.com.therandomlabs.randompatches.core.RPTransformer' was detected and will no longer process meta class data
[04:15:41] [main/INFO]: [team.chisel.ctm.client.asm.CTMTransformer:preTransform:230]: Transforming Class [net.minecraft.client.renderer.texture.TextureMap], Method [registerSprite]
[04:15:41] [main/INFO]: [team.chisel.ctm.client.asm.CTMTransformer:finishTransform:242]: Transforming net.minecraft.client.renderer.texture.TextureMap Finished.
[04:15:41] [main/INFO]: Processing net.minecraft.client.renderer.BlockRendererDispatcher
[04:15:41] [main/INFO]: renderBlockDamage patched
[04:15:41] [main/INFO]: renderBlock patched
[04:15:41] [main/INFO]: Transforming Class [net.minecraft.client.renderer.RenderItem], Method [func_180453_a, func_184391_a]
[04:15:41] [main/INFO]: Transforming net.minecraft.client.renderer.RenderItem Finished.
[04:15:41] [main/INFO]: [team.chisel.ctm.client.asm.CTMTransformer:preTransform:230]: Transforming Class [net.minecraft.block.Block], Method [getExtendedState]
[04:15:41] [main/INFO]: [team.chisel.ctm.client.asm.CTMTransformer:finishTransform:242]: Transforming net.minecraft.block.Block Finished.
[04:15:41] [main/INFO]: [net.wurstclient.forge.asm.WClassTransformer:transform:70]: Transforming net.minecraft.client.entity.EntityPlayerSP, obfuscated=true
[04:15:41] [main/INFO]: [net.wurstclient.forge.asm.EntityPlayerSPVisitor$OnUpdateWalkingPlayerVisitor:visitCode:57]: EntityPlayerSPVisitor.OnUpdateWalkingPlayerVisitor.visitCode()
[04:15:41] [main/INFO]: [net.wurstclient.forge.asm.EntityPlayerSPVisitor$OnUpdateWalkingPlayerVisitor:visitInsn:73]: EntityPlayerSPVisitor.OnUpdateWalkingPlayerVisitor.visitInsn()
[04:15:41] [main/INFO]: [net.wurstclient.forge.asm.EntityPlayerSPVisitor$MoveEntityVisitor:visitCode:98]: EntityPlayerSPVisitor.MoveEntityVisitor.visitCode()
[04:15:41] [main/INFO]: [net.wurstclient.forge.asm.WClassTransformer:transform:70]: Transforming net.minecraft.client.renderer.EntityRenderer, obfuscated=true
[04:15:41] [main/INFO]: [net.wurstclient.forge.asm.EntityRendererVisitor$HurtCameraEffectVisitor:visitCode:48]: EntityRendererVisitor.HurtCameraEffectVisitor.visitCode()
[04:15:41] [main/INFO]: [net.wurstclient.forge.asm.EntityRendererVisitor$SetupCameraTransformVisitor:visitJumpInsn:91]: EntityRendererVisitor.SetupCameraTransformVisitor.visitJumpInsn()
[04:15:41] [main/INFO]: Transmorgrifying [net.minecraft.client.renderer.EntityRenderer]: addRainParticles
[04:15:41] [main/INFO]: func_78484_h()V: Found!
[04:15:41] [main/INFO]: Transmorgrified [net.minecraft.client.renderer.EntityRenderer]: addRainParticles
[04:15:41] [main/INFO]: [net.wurstclient.forge.asm.WClassTransformer:transform:70]: Transforming net.minecraft.client.network.NetHandlerPlayClient, obfuscated=true
[04:15:41] [main/INFO]: [net.wurstclient.forge.asm.NetHandlerPlayClientVisitor$SendPacketVisitor:visitCode:40]: NetHandlerPlayClientVisitor.SendPacketVisitor.visitCode()
[04:15:41] [main/INFO]: [net.wurstclient.forge.asm.WClassTransformer:transform:70]: Transforming net.minecraft.network.NetworkManager, obfuscated=true
[04:15:41] [main/INFO]: [net.wurstclient.forge.asm.NetworkManagerVisitor$ChannelRead0Visitor:visitJumpInsn:48]: NetworkManagerVisitor.ChannelRead0Visitor.visitJumpInsn()
[04:15:41] [main/INFO]: [net.wurstclient.forge.asm.WClassTransformer:transform:70]: Transforming net.minecraft.block.BlockLiquid, obfuscated=true
[04:15:41] [main/INFO]: [net.wurstclient.forge.asm.BlockLiquidVisitor$GetCollisionBoundingBoxVisitor:visitFieldInsn:56]: BlockLiquidVisitor.GetCollisionBoundingBoxVisitor.visitFieldInsn()
[04:15:42] [main/INFO]: [net.wurstclient.forge.asm.WClassTransformer:transform:70]: Transforming net.minecraft.entity.player.EntityPlayer, obfuscated=true
[04:15:42] [main/INFO]: [net.wurstclient.forge.asm.EntityPlayerVisitor$JumpVisitor:visitCode:38]: EntityPlayerVisitor.JumpVisitor.visitCode()
[04:15:42] [main/INFO]: Transforming net.minecraft.entity.player.EntityPlayer finished, added func_184613_cA() overriding EntityLivingBase
[04:15:42] [main/FATAL]: Mixin prepare failed preparing MixinItemStack in mixins.impact.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: mixins.impact.json:MixinItemStack target net.minecraft.item.ItemStack was already transformed.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.impact.json:MixinItemStack target net.minecraft.item.ItemStack was already transformed.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885) ~[Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) ~[Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) ~[Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) ~[Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) ~[Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) [Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) [Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) [Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) [Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [Impact-4.6-1.12.2.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[04:15:42] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.impact.json:MixinItemStack] from phase [DEFAULT] in config [mixins.impact.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779) ~[Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinPrepareError(MixinTransformer.java:728) ~[Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:650) ~[Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) ~[Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) ~[Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) ~[Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[Impact-4.6-1.12.2.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.impact.json:MixinItemStack target net.minecraft.item.ItemStack was already transformed.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885) ~[Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) ~[Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) ~[Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) ~[Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) ~[Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) ~[Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) ~[Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) ~[Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) ~[Impact-4.6-1.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[Impact-4.6-1.12.2.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 6 more
[04:15:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[04:15:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[04:15:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[04:15:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[04:15:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[04:15:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[04:15:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by leijurv** [comment]
don't care lol

**Comment by leijurv** [comment]
https://github.com/ImpactDevelopment/ImpactClient/wiki/Usage-FAQ#impact-crashesdoes-something-weird-when-i-run-it-with-insert-amount-here-other-forge-mods
