### ISSUE TITLE
Edgecase Crash

### ISSUE THREAD

**Issue by Thunder33345** [ImpactDevelopment/ImpactClient#1482]
**Describe the bug**t
A client crash bug,
this crash bug crashes the client when something related to transfering is triggered
theorize it's an edge case 
context, some server tried to rip off 2b queues, but fail to properly spawn in client and crashed it LUL
not expecting to be fixed kek

**Expected behavior**
player just get transferred off queue to main/quit or disconnect if not possible
rather then crashing

<details> 
  <summary><strong>Game output</strong></summary>
 

```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 7/31/19 5:45 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at axy.a(SourceFile:942)
	at ctx.a(SourceFile:137)
	at ctx.a(SourceFile:70)
	at cty.b(SourceFile:889)
	at cty.a(SourceFile:875)
	at cty.a(SourceFile:749)
	at cft.c(SourceFile:850)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at axy.a(SourceFile:942)
	at ctx.a(SourceFile:137)
	at ctx.a(SourceFile:70)
	at cty.b(SourceFile:889)
	at cty.a(SourceFile:875)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [ctj['Thunder33345'/0, l='MpServer', x=176.10, y=203.00, z=-26.89]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (4208,68,403), Chunk: (at 0,4,3 in 263,25; contains blocks 4208,0,400 to 4223,255,415), Region: (8,0; contains chunks 256,0 to 287,31, blocks 4096,0,0 to 4607,255,511)
	Level time: 113969 game time, 46243939 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [ctj['Thunder33345'/0, l='MpServer', x=176.10, y=203.00, z=-26.89]]
	Retry entities: 0 total; []
	Server brand: Waterdog (git:Waterdog-Bootstrap:1.14-SNAPSHOT:97bdf54:248) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at crg.a(SourceFile:418)
	at cft.b(SourceFile:1815)
	at cft.a(SourceFile:408)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 363883576 bytes (347 MB) / 771751936 bytes (736 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.13.2-Impact_4.8.0-20190727-nightly
	LWJGL: 3.1.6 build 14
	OpenGL: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.60, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

see before https://paste.ubuntu.com/p/nm7jW5GjMv/
```
[...]
[17:46:16] [main/INFO]: Loaded 348 advancements
[17:46:16] [main/INFO]: [CHAT] Welcome, Thunder33345!
[17:46:16] [main/INFO]: [CHAT] Use /mail to message offline players.
[17:46:16] [main/INFO]: [CHAT] Type /optimize to open lag manager.
[17:46:16] [main/INFO]: [CHAT] Type /seen for player's last seen time.
[17:46:16] [main/INFO]: [CHAT] Type /tps to view the server's tps.
[17:46:16] [main/INFO]: [CHAT] Type /sc to toggle your coordinates.
[17:46:16] [main/INFO]: [CHAT] Players online: 1
[17:46:16] [main/INFO]: [CHAT] You have 1 messages! Type /mail read to view your mail.
[17:46:18] [main/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: null
	at axy.a(SourceFile:942) ~[axy.class:?]
	at ctx.a(SourceFile:137) ~[ctx.class:?]
	at ctx.a(SourceFile:70) ~[ctx.class:?]
	at cty.b(SourceFile:889) ~[cty.class:?]
	at cty.a(SourceFile:875) ~[cty.class:?]
	at cty.a(SourceFile:749) ~[cty.class:?]
	at cft.c(SourceFile:850) ~[cft.class:?]
	at cft.a(SourceFile:395) [cft.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.8 nightly for 1.13.2 but seems to be reproducable by wide range
- Using Optifine?  no
- Using LiteLoader?  no
- Operating System:  win10 64bit

</details>

**Additional context**
just some edge case shit that happens on a small random 2b ripoff server kek
> omega high IQ: Play on 2b ripoff

**Comment by 0-x-2-2** [comment]
This crashes in Minecraft code.
