### ISSUE TITLE
Impact crashes on launch

### ISSUE THREAD

**Issue by greenkeep** [ImpactDevelopment/ImpactClient#1536]
**Describe the bug**
Ok, I installed impact 4.7, but whenever I launch it it crashese after a few seconds

**To Reproduce**
1. Install impact 4.7 or 4.6 using the installer(vanilla not forge)
2. Select Impact 4.7/4.6 on your launcher
3. click play

**Expected behavior**
I expected it to launch like usual

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

``18:21:26.523
Preparing to launch minecraft client for 1.12.2-Impact_4.7.2
18:21:27.741
Couldn't fetch SHA1 checksum for https://s3.amazonaws.com/Minecraft.Download/versions/1.12.2/1.12.2.jar
18:21:27.743
Have local file C:\Users\colin\AppData\Roaming\.minecraft\versions\1.12.2\1.12.2.jar but don't know what size or hash it should be. Have to assume it's good.
18:21:50.827
Checking installations.
18:21:50.829
Minecraft client 1.12.2-Impact_4.7.2 is ready to start.
18:21:50.829
Starting!
18:21:51.991
Using default game log configuration client-1.12.xml (outputs XML)
18:21:54.950
Loading tweak class name clientapi.load.ClientTweaker
18:21:55.022
Using primary tweak class name clientapi.load.ClientTweaker
18:21:55.022
Loading tweak class name baritone.launch.BaritoneTweaker
18:21:55.025
Calling tweak class clientapi.load.ClientTweaker
18:21:55.053
Injecting into ClassLoader
18:21:55.740
SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/colin/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
18:22:03.681
FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
18:22:03.782
Initialized Mixin bootstrap
18:22:03.981
Setup Mixin Environment
18:22:04.138
Registered Bytecode Transformes
18:22:04.191
Compatibility level set to JAVA_8
18:22:04.198
Mixin config mixins.impact.json does not specify "minVersion" property
18:22:04.198
Loaded Mixin Configurations
18:22:04.199
Calling tweak class baritone.launch.BaritoneTweaker
18:22:04.210
Mixin config mixins.baritone.json does not specify "minVersion" property
18:22:04.213
Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
18:22:04.215
Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
18:22:04.644
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinBlock, name: clientapi.load.mixin.MixinBlock
18:22:04.878
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntity, name: clientapi.load.mixin.MixinEntity
18:22:04.998
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntityLivingBase, name: clientapi.load.mixin.MixinEntityLivingBase
18:22:05.023
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntityPlayerSP, name: clientapi.load.mixin.MixinEntityPlayerSP
18:22:05.034
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntityRenderer, name: clientapi.load.mixin.MixinEntityRenderer
18:22:05.131
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinFontRenderer, name: clientapi.load.mixin.MixinFontRenderer
18:22:05.180
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinGuiBossOverlay, name: clientapi.load.mixin.MixinGuiBossOverlay
18:22:05.187
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinGuiIngame, name: clientapi.load.mixin.MixinGuiIngame
18:22:05.198
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinGuiSpectator, name: clientapi.load.mixin.MixinGuiSpectator
18:22:05.215
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinItemRenderer, name: clientapi.load.mixin.MixinItemRenderer
18:22:05.224
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinLayerArmorBase, name: clientapi.load.mixin.MixinLayerArmorBase
18:22:05.232
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinMinecraft, name: clientapi.load.mixin.MixinMinecraft
18:22:05.312
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNetHandlerLoginClient, name: clientapi.load.mixin.MixinNetHandlerLoginClient
18:22:05.319
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNetHandlerPlayClient, name: clientapi.load.mixin.MixinNetHandlerPlayClient
18:22:05.334
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNettyPacketDecoder, name: clientapi.load.mixin.MixinNettyPacketDecoder
18:22:05.344
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNettyPacketEncoder, name: clientapi.load.mixin.MixinNettyPacketEncoder
18:22:05.353
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNetworkManager, name: clientapi.load.mixin.MixinNetworkManager
18:22:05.391
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinParticleManager, name: clientapi.load.mixin.MixinParticleManager
18:22:05.399
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinRender, name: clientapi.load.mixin.MixinRender
18:22:05.408
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinRenderItem, name: clientapi.load.mixin.MixinRenderItem
18:22:05.418
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinRenderLivingBase, name: clientapi.load.mixin.MixinRenderLivingBase
18:22:05.425
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinRenderManager, name: clientapi.load.mixin.MixinRenderManager
18:22:05.441
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinTimer, name: clientapi.load.mixin.MixinTimer
18:22:06.065
Error loading class: Config (java.lang.ClassNotFoundException: The specified class 'Config' was not found)
18:22:06.068
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinAnvilChunkLoader, name: baritone.launch.mixins.MixinAnvilChunkLoader
18:22:06.082
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinBlockPos, name: baritone.launch.mixins.MixinBlockPos
18:22:06.089
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChunkProviderClient, name: baritone.launch.mixins.MixinChunkProviderClient
18:22:06.097
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChunkProviderServer, name: baritone.launch.mixins.MixinChunkProviderServer
18:22:06.107
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChunkRenderContainer, name: baritone.launch.mixins.MixinChunkRenderContainer
18:22:06.164
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChunkRenderWorker, name: baritone.launch.mixins.MixinChunkRenderWorker
18:22:06.170
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntityLivingBase, name: baritone.launch.mixins.MixinEntityLivingBase
18:22:06.175
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntityPlayerSP, name: baritone.launch.mixins.MixinEntityPlayerSP
18:22:06.182
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntityRenderer, name: baritone.launch.mixins.MixinEntityRenderer
18:22:06.186
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinMinecraft, name: baritone.launch.mixins.MixinMinecraft
18:22:06.190
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinNetHandlerPlayClient, name: baritone.launch.mixins.MixinNetHandlerPlayClient
18:22:06.196
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinNetworkManager, name: baritone.launch.mixins.MixinNetworkManager
18:22:06.202
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinRenderChunk, name: baritone.launch.mixins.MixinRenderChunk
18:22:06.209
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinRenderList, name: baritone.launch.mixins.MixinRenderList
18:22:06.215
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinVboRenderList, name: baritone.launch.mixins.MixinVboRenderList
18:22:06.221
Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinWorldClient, name: baritone.launch.mixins.MixinWorldClient
18:22:06.638
Launching wrapped minecraft {net.minecraft.client.main.Main}
18:22:11.413
Setting user: greenkeep
18:22:17.616
Skipping bad option: lastServer:
18:22:17.678
LWJGL Version: 2.9.4
18:22:19.169
Reloading ResourceManager: Default
18:22:21.645
Starting up SoundSystem...
18:22:21.949
Initializing LWJGL OpenAL
18:22:21.950
(The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
18:22:22.975
OpenAL initialized.
18:22:23.226
Sound engine started
18:22:35.178
Created: 1024x512 textures-atlas
18:22:40.838
Narrator library for x64 successfully loaded
18:22:42.145
[STDOUT]: Baritone settings file not found, resetting.
18:22:44.285
Loading Fonts
18:22:45.574
Loading Users
18:22:45.763
Checking for Updates
18:22:45.768
[STDOUT]: Offering updates to betas: false
18:22:46.172
[STDOUT]: Fetching releases from ImpactDevelopment/ImpactReleases
18:22:46.175
[STDOUT]: DOWNLOADING https://api.github.com/repos/ImpactDevelopment/ImpactReleases/releases
18:22:48.780
<log4j:Event logger="no" timestamp="1565691768779" level="INFO" thread="main">
    <log4j:Message><![CDATA[[STDERR]: impact.3M: ERROR: 0:3: 'out' : syntax error parse error
]]></log4j:Message>
  </log4j:Event>
18:22:48.780
XML_ERROR_PARSING_CDATA
18:22:48.780
[STDERR]: 	at impact.73.0(Unknown Source)
18:22:48.782
[STDERR]: 	at impact.3r.0(Unknown Source)
18:22:48.782
[STDERR]: 	at impact.3w.2(Unknown Source)
18:22:48.783
[STDERR]: 	at impact.3L.<init>(Unknown Source)
18:22:48.783
[STDERR]: 	at impact.3j.<init>(Unknown Source)
18:22:48.784
[STDERR]: 	at impact.3j.<init>(Unknown Source)
18:22:48.785
[STDERR]: 	at impact.9R.<init>(Unknown Source)
18:22:48.786
[STDERR]: 	at impact.4p.2(Unknown Source)
18:22:48.786
[STDERR]: 	at impact.5o.0(Unknown Source)
18:22:48.786
[STDERR]: 	at impact.4z.0(Unknown Source)
18:22:48.787
[STDERR]: 	at bib.handler$init$zzl000(SourceFile:3097)
18:22:48.787
[STDERR]: 	at bib.aq(SourceFile:583)
18:22:48.787
[STDERR]: 	at bib.a(SourceFile:404)
18:22:48.788
[STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
18:22:48.788
[STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:22:48.788
[STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:22:48.789
[STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:22:48.789
[STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
18:22:48.789
[STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
18:22:48.790
[STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
18:22:48.792
[STDERR]: impact.3M: Cannot attach a shader to program if shader isn't generated!
18:22:48.793
[STDERR]: 	at impact.3_.0(Unknown Source)
18:22:48.793
[STDERR]: 	at impact.3_$$Lambda$232/426056157.accept(Unknown Source)
18:22:48.793
[STDERR]: 	at java.util.ArrayList.forEach(ArrayList.java:1249)
18:22:48.793
[STDERR]: 	at impact.3_.0(Unknown Source)
18:22:48.793
[STDERR]: 	at impact.3w.2(Unknown Source)
18:22:48.793
[STDERR]: 	at impact.3j.<init>(Unknown Source)
18:22:48.821
[STDERR]: 	at impact.9R.<init>(Unknown Source)
18:22:48.821
[STDERR]: 	at impact.4p.2(Unknown Source)
18:22:48.821
[STDERR]: 	at impact.5o.0(Unknown Source)
18:22:48.821
[STDERR]: 	at impact.4z.0(Unknown Source)
18:22:48.821
[STDERR]: 	at bib.handler$init$zzl000(SourceFile:3097)
18:22:48.821
[STDERR]: 	at bib.aq(SourceFile:583)
18:22:48.821
[STDERR]: 	at bib.a(SourceFile:404)
18:22:48.821
[STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
18:22:48.822
[STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:22:48.822
[STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:22:48.822
[STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:22:48.822
[STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
18:22:48.822
[STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
18:22:48.822
[STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
18:22:48.862
Initialized 117 mods!
18:22:49.646
Unable to load spam config file: Spam config file is in invalid format
18:22:52.186
[STDOUT]: Initializing took 10169ms
18:22:52.408
########## GL ERROR ##########
18:22:52.409
@ Pre render
18:22:52.409
1282: Invalid operation
18:22:54.454

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000020cfd453, pid=9876, tid=9900
#
# JRE version: Java(TM) SE Runtime Environment (8.0_51-b16) (build 1.8.0_51-b16)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.51-b03 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ig4icd64.dll+0x73d453]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\colin\AppData\Roaming\.minecraft\hs_err_pid9876.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
AL lib: (EE) alc_cleanup: 1 device not closed
18:22:54.457
Process crashed with exit code 1

``

 

- Impact Version: <4.6 and 4.7>
- Using Optifine? <no>
- Using LiteLoader? <no>
- Enabled mods: <none, deleted my .minecraft folder prior to installing>
- Operating System: <Windows 10 64bit>

</details>

**Additional context**
-

**Comment by greenkeep** [comment]
I was not using optifine btw, forgot to list it
