### ISSUE TITLE
[4.1] jesus sometimes crashes with IllegalArgumentException

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#165]
When falling from height into flowing lava with solid blocks below, so that I take fall damage at the same time as landing in the lava, Solid Jesus crashes trying to run `state.getValue(BlockLiquid.LEVEL) == 0`.

This may be reproducible in other ways, but I wanted to log the issue before investigating further, while I still had the stacktrace. I've only seen this on the latest Impact master.

```
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=level, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:185) ~[BlockStateContainer$StateImplementation.class:?]
	at me.zero.clarinet.mod.impl.movement.jesus.JesusSolid.lambda$new$0(JesusSolid.java:40) ~[JesusSolid.class:?]
```

**Comment by ZeroMemes** [comment]
Fixed in 4.1
