### ISSUE TITLE
Crash(with log)

### ISSUE THREAD

**Issue by Thunder33345** [ImpactDevelopment/ImpactClient#213]
Crash:
Description: Ticking entity, java.lang.NullPointerException: Ticking entity

My client crashes,
When I join a specific server

### Exact steps to reproduce?
Joining a specific server
sorry cant really describe this any better
this also doesn't affect my ability to join some other servers OR single player world
rejoining it will lead to the same crash
my friend was able to join the same server with no problem

### Crash Log
(crash2)

23:39:00 | bkr | main | info | Connecting to [redacted], 25565
-- | -- | -- | -- | --
23:39:04 | j | main | info | Loaded 327 advancements
23:39:06 | bib | main | fatal | Reported exception thrown! f: Ticking entity 	at amu.k(SourceFile:1389) 	at bib.t(SourceFile:1691) 	at bib.az(SourceFile:1000) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: java.lang.NullPointerException 	at me.zero.clarinet.bS.lambda$new$1(bS.java) 	at me.zero.clarinet.bS$$Lambda$144/1135858071.invoke(Unknown Source) 	at me.zero.alpine.listener.Listener.invoke(Listener.java:77) 	at me.zero.alpine.EventManager.lambda$post$6(EventManager.java:98) 	at me.zero.alpine.EventManager$$Lambda$95/53903834.accept(Unknown Source) 	at java.util.ArrayList.forEach(ArrayList.java:1249) 	at me.zero.alpine.EventManager.post(EventManager.java:98) 	at me.zero.client.api.event.CAPIEventManager.post(CAPIEventManager.java:34) 	at bud.handler$onUpdate$zzd000(SourceFile:1220) 	at bud.B_(SourceFile) 	at amu.a(SourceFile:1523) 	at amu.h(SourceFile:1499) 	at amu.k(SourceFile:1382) 	... 10 more

### Crash report?

(crash1)
```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 9/6/17 11:17 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at me.zero.clarinet.bS.lambda$new$1(bS.java)
	at me.zero.clarinet.bS$$Lambda$144/1135858071.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:77)
	at me.zero.alpine.EventManager.lambda$post$6(EventManager.java:98)
	at me.zero.alpine.EventManager$$Lambda$95/53903834.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at me.zero.alpine.EventManager.post(EventManager.java:98)
	at me.zero.client.api.event.CAPIEventManager.post(CAPIEventManager.java:34)
	at bud.handler$onUpdate$zzd000(SourceFile:1220)
	at bud.B_(SourceFile)
	at amu.a(SourceFile:1523)
	at amu.h(SourceFile:1499)
	at amu.k(SourceFile:1382)
	at bib.t(SourceFile:1691)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at me.zero.clarinet.bS.lambda$new$1(bS.java)
	at me.zero.clarinet.bS$$Lambda$144/1135858071.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:77)
	at me.zero.alpine.EventManager.lambda$post$6(EventManager.java:98)
	at me.zero.alpine.EventManager$$Lambda$95/53903834.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at me.zero.alpine.EventManager.post(EventManager.java:98)
	at me.zero.client.api.event.CAPIEventManager.post(CAPIEventManager.java:34)
	at bud.handler$onUpdate$zzd000(SourceFile:1220)
	at bud.B_(SourceFile)
	at amu.a(SourceFile:1523)
	at amu.h(SourceFile:1499)

-- Entity being ticked --
Details:
	Entity Type: null (me.zero.clarinet.hook.b)
	Entity ID: 1611301
	Entity Name: Thunder33345
	Entity's Exact location: 0.00, 1.00, 0.00
	Entity's Block location: World: (0,1,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at amu.k(SourceFile:1382)
	at bib.t(SourceFile:1691)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 332152560 bytes (316 MB) / 555499520 bytes (529 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.12.1-Impact_4.1-OF
	LWJGL: 2.9.4
	OpenGL: GeForce GT 720M/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.54, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: VanillaTweaks.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz
	OptiFine Version: OptiFine_1.12.1_HD_U_C5
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 353.54
	OpenGlRenderer: GeForce GT 720M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
```
[crash2](https://ghostbin.com/paste/4zn34) (because i dont didnt saved the logs for crash1 but it seem to be same)
- Impact Version: 4.1 for 1.12.1
- Using Optifine? Yes
- Enabled mods: [Mods.json](https://ghostbin.com/paste/j85cx)
- Operating System: Windows 10 (amd64) version 10.0

**Comment by Thunder33345** [comment]
apparent that's solved when i deleted renamed the old impact folder
here's most of my files
https://gist.github.com/Thunder33345/2eb2cc7fc745826c52a1d77b42406308
closed for now as it's self resloved

**Comment by LeafHacker** [comment]
Looks like mc.player was being ticked and one of our event (`UpdateEvent`?) handlers tried to access a something that hadn't been initialised yet without checking if it was null (or catching exceptions).

TBH IMO the event manager should wrap all event listeners in a catchall `try` block so that rogue event handlers can't crash the client without explicitly calling `exit`. Modules shouldn't be able to accidentally crash.

**Comment by ZeroMemes** [comment]
Appears to be caused by the ``UpdateEvent`` Listener in AutoFish, being a ``NullPointerException``, it should be easy to fix.

**Comment by LeafHacker** [comment]
Still, rogue event handlers, modules, etc should really be wrapped in
try...catch blocks anyway. Some random module throwing a NPE doesn't help
anyone.

**Comment by ZeroMemes** [comment]
Looking at the code I don't see anything that could cause a nullpointer. The ``UpdateEvent`` is called pre ``onUpdate`` for all instances of ``EntityPlayerSP``, which are constructed by ``PlayerControllerMP``. There is a null check for the client player ``fishEntity``, so that can't be the cause... any thoughts @LeafHacker? I can't find anything that could've caused it.

**Comment by w-o-a-h** [comment]
it seems it was a config issue

**Comment by ZeroMemes** [comment]
It must've been, but I don't know how it could've lead to a NPE

**Comment by LeafHacker** [comment]
I'll try and take a look over the weekend of I get chance

**Comment by ZeroMemes** [comment]
Fixed the only thing that could've caused the problem.
