### ISSUE TITLE
Optifine Tweak does not work with 4.1

### ISSUE THREAD

**Issue by zPeanut** [ImpactDevelopment/ImpactClient#239]
```
[15:53:14] [main/INFO]: Loading tweak class name me.zero.client.load.ClientTweaker
[15:53:14] [main/INFO]: Using primary tweak class name me.zero.client.load.ClientTweaker
[15:53:14] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[15:53:14] [main/INFO]: Calling tweak class me.zero.client.load.ClientTweaker
[ClientAPI][INFO] Injecting into ClassLoader 
[15:53:14] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.1 Source=file:/C:/Users/Mustafa/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.7.1-SNAPSHOT/mixin-0.7.1-SNAPSHOT.jar Env=UNKNOWN
[15:53:14] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[15:53:14] [main/INFO]: Compatibility level set to JAVA_8
[15:53:14] [main/ERROR]: Mixin config mixins.capi.json does not specify "minVersion" property
[15:53:14] [main/ERROR]: Mixin config mixins.client.json does not specify "minVersion" property
[15:53:14] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
OptiFineTweaker: acceptOptions
OptiFineTweaker: injectIntoClassLoader
OptiFine ClassTransformer
OptiFine URL: file:/C:/Users/gay/AppData/Roaming/.minecraft/libraries/optifine/OptiFine/1.12.1_HD_U_C5/OptiFine-1.12.1_HD_U_C5.jar
OptiFine ZIP file: C:\Users\gay\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.12.1_HD_U_C5\OptiFine-1.12.1_HD_U_C5.jar
[15:53:14] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
[15:53:14] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
OptiFineTweaker: getLaunchArguments
[15:53:14] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[15:53:15] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: joptsimple.MultipleArgumentsForOptionException: Found multiple arguments for option version, but you asked for only one
	at joptsimple.OptionSet.valueOf(OptionSet.java:179) ~[OptionSet.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:86) ~[Main.class:?]
	... 6 more
Java HotSpot(TM) Client VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

```

**Comment by SuperOP535** [comment]
works for me 🤔

**Comment by LeafHacker** [comment]
This is invalid. You are loading OptiFineTweaker instead of
OptiFineForgeTweaker (or whatever it's called)

On 15 Sep 2017 14:54, "Peanut" <notifications@github.com> wrote:

[15:53:14] [main/INFO]: Loading tweak class name
me.zero.client.load.ClientTweaker
[15:53:14] [main/INFO]: Using primary tweak class name
me.zero.client.load.ClientTweaker
[15:53:14] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[15:53:14] [main/INFO]: Calling tweak class me.zero.client.load.ClientTweaker
[ClientAPI][INFO] Injecting into ClassLoader
[15:53:14] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.1
Source=file:/C:/Users/Mustafa/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.7.1-SNAPSHOT/mixin-0.7.1-SNAPSHOT.jar
Env=UNKNOWN
[15:53:14] [main/INFO]: FML platform manager could not load class
cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML
support.
[15:53:14] [main/INFO]: Compatibility level set to JAVA_8
[15:53:14] [main/ERROR]: Mixin config mixins.capi.json does not
specify "minVersion" property
[15:53:14] [main/ERROR]: Mixin config mixins.client.json does not
specify "minVersion" property
[15:53:14] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
OptiFineTweaker: acceptOptions
OptiFineTweaker: injectIntoClassLoader
OptiFine ClassTransformer
OptiFine URL: file:/C:/Users/Mustafa/AppData/Roaming/.minecraft/libraries/optifine/OptiFine/1.12.1_HD_U_C5/OptiFine-1.12.1_HD_U_C5.jar
OptiFine ZIP file:
C:\Users\Mustafa\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.12.1_HD_U_C5\OptiFine-1.12.1_HD_U_C5.jar
[15:53:14] [main/INFO]: Loading tweak class name
org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
[15:53:14] [main/INFO]: Calling tweak class
org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
OptiFineTweaker: getLaunchArguments
[15:53:14] [main/INFO]: Launching wrapped minecraft
{net.minecraft.client.main.Main}
[15:53:15] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[launchwrapper-1.12.jar:?]
Caused by: joptsimple.MultipleArgumentsForOptionException: Found
multiple arguments for option version, but you asked for only one
	at joptsimple.OptionSet.valueOf(OptionSet.java:179) ~[OptionSet.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:86) ~[Main.class:?]
	... 6 more
Java HotSpot(TM) Client VM warning: Using incremental CMS is
deprecated and will likely be removed in a future release


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ImpactDevelopment/ImpactClient/issues/239>, or mute the
thread
