### ISSUE TITLE
Autofish has a long delay before reeling in. This causes fish to be lost.

### ISSUE THREAD

**Issue by GlitchHead** [ImpactDevelopment/ImpactClient#426]
### What happens?

When a fish hooks onto your fishing rod autofish waits for a long time before reeling in. This causes you to loose fish. It should be instant.
### When does this happen?

When using autofish
### Exact steps to reproduce?
Move to water and get a fishing rod and enable autofish.

### Game output?

```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 10/14/17 5:42 PM
Description: Manually triggered debug crash

java.lang.Throwable
	at bib.aD(SourceFile:1745)
	at bib.t(SourceFile:1665)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at bib.aD(SourceFile:1745)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [b['Player'/42572, l='MpServer', x=-170.47, y=62.07, z=283.35]]
	Chunk stats: MultiplayerChunkCache: 282, 282
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (21,64,201), Chunk: (at 5,4,9 in 1,12; contains blocks 16,0,192 to 31,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 297083 game time, 103035 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 12 total; [b['Player'/42572, l='MpServer', x=-170.47, y=62.07, z=283.35], aag['Sheep'/44099, l='MpServer', x=-209.55, y=63.00, z=335.59], aag['Sheep'/44100, l='MpServer', x=-210.60, y=63.00, z=335.50], aad['Pig'/42193, l='MpServer', x=-97.75, y=64.00, z=316.34], aad['Pig'/42194, l='MpServer', x=-102.72, y=64.00, z=308.63], afd['Boat'/44631, l='MpServer', x=-170.47, y=62.52, z=283.35], aag['Sheep'/44130, l='MpServer', x=-213.50, y=63.00, z=338.50], aag['Sheep'/44131, l='MpServer', x=-209.50, y=63.00, z=339.50], aad['Pig'/44132, l='MpServer', x=-114.72, y=69.00, z=344.16], aad['Pig'/44133, l='MpServer', x=-115.49, y=68.00, z=336.77], aad['Pig'/44134, l='MpServer', x=-118.29, y=69.00, z=345.49], aad['Pig'/44135, l='MpServer', x=-104.84, y=70.00, z=343.43]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at bsb.a(SourceFile:366)
	at bib.b(SourceFile:2587)
	at bib.a(SourceFile:428)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 298995136 bytes (285 MB) / 950525952 bytes (906 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	Launched Version: 1.12.2-Impact_4.1
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 760/PCIe/SSE2 GL version 4.5.0 NVIDIA 381.65, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
```

- Impact Version:  4.1 1.12.2
- Using Optifine?  Yes
- Enabled mods:  Autofish
- Operating System:  Windows 10 64 bit

**Comment by SuperOP535** [comment]
I think autofish is not made for fishing, it is made for combat

**Comment by VitorISs** [comment]
No, @SuperOP535 , its made for fishing..

**Comment by mrx12335** [comment]
This happens to me too when the TPS of the server is very low

**Comment by GlitchHead** [comment]
Is this going to be fixed?

**Comment by ZeroMemes** [comment]
I'll try to find a better method to detect when the fish takes the bait on servers with lower TPS. On a singleplayer game there were no issues with reel delay.

**Comment by LeafHacker** [comment]
atm I had just set it up with a rtc timer running in a second thread. In theory this could be multiplied by the TPS percentage.

**Comment by VincentCCandela** [comment]
I'm having a similar issue on a 1.13 server. The fish bite sound plays but autofish does not reel in despite a zero reel in delay and the nearby option being turned off. Perhaps the fish bite sound has changed?

**Comment by LeafHacker** [comment]
Closing because catch delay is configurable now
