### ISSUE TITLE
Crashing on non-full block's

### ISSUE THREAD

**Issue by SquidingTin** [ImpactDevelopment/ImpactClient#466]
<-- Client crashes when the user touches any non full block -->

### Exact steps to reproduce?

- Turn on auto tool
- Touch a non-full block
- Crash

### Game output?

```
**
	at me.zero.clarinet.v.lambda$new$0(v.java)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:77)
	at me.zero.alpine.EventManager.lambda$post$6(EventManager.java:98)
	at java.util.ArrayList.forEach(Unknown Source)
	at me.zero.alpine.EventManager.post(EventManager.java:98)
	at me.zero.client.api.event.CAPIEventManager.post(CAPIEventManager.java:34)
	at bud.handler$onUpdate$zzd000(SourceFile:1224)
	at bud.B_(SourceFile)
	at amu.a(SourceFile:1524)
	at amu.h(SourceFile:1500)
	at amu.k(SourceFile:1382)
	at bib.t(SourceFile:1691)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
**
```

### Crash report?

```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 11/9/17 10:35 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at me.zero.clarinet.v.lambda$new$0(v.java)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:77)
	at me.zero.alpine.EventManager.lambda$post$6(EventManager.java:98)
	at java.util.ArrayList.forEach(Unknown Source)
	at me.zero.alpine.EventManager.post(EventManager.java:98)
	at me.zero.client.api.event.CAPIEventManager.post(CAPIEventManager.java:34)
	at bud.handler$onUpdate$zzd000(SourceFile:1224)
	at bud.B_(SourceFile)
	at amu.a(SourceFile:1524)
	at amu.h(SourceFile:1500)
	at amu.k(SourceFile:1382)
	at bib.t(SourceFile:1691)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:

---------------------------------------------------------------------------------------


-- Head --

Thread: Client thread

Stacktrace:
	
at me.zero.clarinet.v.lambda$new$0(v.java)
	
at me.zero.alpine.listener.Listener.invoke(Listener.java:77)
	
at me.zero.alpine.EventManager.lambda$post$6(EventManager.java:98)
	
at java.util.ArrayList.forEach(Unknown Source)
	
at me.zero.alpine.EventManager.post(EventManager.java:98)
	
at me.zero.client.api.event.CAPIEventManager.post(CAPIEventManager.java:34)
	at bud.handler$onUpdate$zzd000(SourceFile:1224)
	
at bud.B_(SourceFile)
	
at amu.a(SourceFile:1524)
	
at amu.h(SourceFile:1500)


-- Entity being ticked --

Details:
	
Entity Type: null (me.zero.clarinet.hook.b)
	
Entity ID: 10591793
	
Entity Name: Squid_Does0MC
	
Entity's Exact location: 150032.88, 23.08, -33.30
	
Entity's Block location: World: (150032,23,-34), Chunk: (at 0,1,14 in 9377,-3; contains blocks 150032,0,-48 to 150047,255,-33), Region: (293,-1; contains chunks 9376,-32 to 9407,-1, blocks 150016,0,-512 to 150527,255,-1)
	
Entity's Momentum: 0.00, 0.00, 0.00
	
Entity's Passengers: []
	
Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at amu.k(SourceFile:1382)


-- Affected level --

Details:
	
Level name: MpServer
	
All players: 1 total; [b['Squid_Does0MC'/10591793, l='MpServer', x=150032.88, y=23.08, z=-33.30]]
	
Chunk stats: MultiplayerChunkCache: 2, 2
	
Level seed: 0
	
Level generator: ID 00 - default, ver 1. Features enabled: false
	
Level generator options: 
	
Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	
Level time: 123390 game time, 907002184 day time
	
Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	
Forced entities: 1 total; [b['Squid_Does0MC'/10591793, l='MpServer', x=150032.88, y=23.08, z=-33.30]]
	
Retry entities: 0 total; []
	
Server brand: Waterfall (git:Waterfall-Bootstrap:1.12-SNAPSHOT:672e94b:154) <- Paper
	
Server type: Non-integrated multiplayer server
Stacktrace:
	
at bsb.a(SourceFile:366)
	
at bib.b(SourceFile:2587)
	
at bib.a(SourceFile:428)
	
at net.minecraft.client.main.Main.main(SourceFile:123)
	
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	
at java.lang.reflect.Method.invoke(Unknown Source)
	
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


-- System Details --

Details:
	
Minecraft Version: 1.12.2
	
Operating System: Windows 8.1 (amd64) version 6.3
	
Java Version: 1.8.0_91, Oracle Corporation
	
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	
Memory: 211898056 bytes (202 MB) / 462024704 bytes (440 MB) up to 2134114304 bytes (2035 MB)
	
JVM Flags: 6 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	
IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	
Launched Version: 1.12.2-Impact_4.1
	
LWJGL: 2.9.4
	
OpenGL: AMD Radeon R7 200 Series GL version 4.5.13416 Compatibility Profile Context 15.300.1025.1001, ATI Technologies Inc.
	
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	
Using VBOs: No
	
Is Modded: Very likely; Jar signature invalidated
	
Type: Client (map_client.txt)
	
Resource Packs: N/A
	
Current Language: English (US)
	
Profiler Position: N/A (disabled)
	
CPU: 4x Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz
```

- Impact Version: 
- Using Optifine? 
- Enabled mods: 
- Operating System:

**Comment by ZeroMemes** [comment]
By non-full block you mean anything without a 1x1x1m size bounding box? Like a ladder per se.

**Comment by SquidingTin** [comment]
more like any block that isn't a full block, stairs aren't that way though and cant seem to find out why stairs are ok
