### ISSUE TITLE
Client crashing on startup

### ISSUE THREAD

**Issue by spymaster1020** [ImpactDevelopment/ImpactClient#505]
### What happens?
Client Crashes

### When does this happen?
on loading up minecraft

### Exact steps to reproduce?

- Install Impact
- Run game as usual

### Game output?

```

```

### Crash report?

```
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2/5/18 1:52 PM
Description: Initializing game

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 447 column 6 path $.levitation control.bind
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at me.zero.clarinet.e7.b(e7.java)
	at me.zero.clarinet.cq.load(cq.java)
	at me.zero.clarinet.a3.load(a3.java)
	at me.zero.clarinet.Impact.onInit(Impact.java)
	at bib.handler$init$zzj000(SourceFile:3234)
	at bib.aq(SourceFile:583)
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 447 column 6 path $.levitation control.bind
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1017)
	at com.google.gson.stream.JsonReader.nextName(JsonReader.java:787)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 16 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at me.zero.clarinet.e7.b(e7.java)
	at me.zero.clarinet.cq.load(cq.java)
	at me.zero.clarinet.a3.load(a3.java)
	at me.zero.clarinet.Impact.onInit(Impact.java)
	at bib.handler$init$zzj000(SourceFile:3234)
	at bib.aq(SourceFile:583)

-- Initialization --
Details:
Stacktrace:
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 132204320 bytes (126 MB) / 285212672 bytes (272 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.12.2-Impact_4.1
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R9 260 GL version 4.5.13497 Compatibility Profile Context 23.20.793.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: VanillaTweaks_63233.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A10-7850K Radeon R7, 12 Compute Cores 4C+8G

```

- Impact Version: 
4.1 for 1.12.2

- Using Optifine?
tested with and without optifine, still crashing.

- Enabled mods: 
Optifine

- Operating System:
Windows 10 64Bit

**Comment by ZeroMemes** [comment]
Can you provide a pastebin/hastebin of your config file? You can find it by going to your minecraft install dir, then navigating to the "Impact" folder and opening "mods.json" The error looks like it's with the JSON parsing, and your config might be corrupted.

**Comment by spymaster1020** [comment]
https://pastebin.com/eM1vHMv2

**Comment by ZeroMemes** [comment]
The JSON file appears to be invalid and you'll have to delete it, I've fixed the issue with the invalid JSON error handling in 4.2.
