### ISSUE TITLE
Client crash in friend-menu

### ISSUE THREAD

**Issue by LordQuadrato** [ImpactDevelopment/ImpactClient#550]
### What happens?
The client crashes when clicking either the _remove_ or _edit_ button in the **friend menu**. Note that the problem only occurs when no friends are added yet.

Just a minor bug. But it is annoying, especially because it crashes and I have to restart the client. Counter-intuitive.

### Exact steps to reproduce?
1. Make sure that there are **no friends** in the friends-menu (like in the picture)
2. Click on either _remove_ or _edit_
3. Your client will crash

![2018-04-24_14 36 15](https://user-images.githubusercontent.com/38622942/39187450-ab9b7116-47cd-11e8-85ad-81694c6a844e.png)
### Game output?

```

14:35:22	launcher	Preparing to launch minecraft client for 1.12.2-Impact_4.2
14:35:23	launcher	Checking installations.
14:35:23	launcher	Minecraft client 1.12.2-Impact_4.2 is ready to start.
14:35:23	launcher	Starting!
14:35:23	launcher	Using default game log configuration client-1.12.xml (outputs XML)
14:35:24	LaunchWrapper	Loading tweak class name clientapi.load.ClientTweaker
14:35:24	LaunchWrapper	Using primary tweak class name clientapi.load.ClientTweaker
14:35:24	LaunchWrapper	Calling tweak class clientapi.load.ClientTweaker
14:35:24	ClientAPI	Injecting into ClassLoader
14:35:24	mixin	SpongePowered MIXIN Subsystem Version=0.7.7 Source=file:/C:/Users/Alex/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.7.7-SNAPSHOT/mixin-0.7.7-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
14:35:25	mixin	FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
14:35:25	ClientAPI	Initialized Mixin bootstrap
14:35:25	mixin	Compatibility level set to JAVA_8
14:35:25	mixin	Mixin config mixins.capi.json does not specify "minVersion" property
14:35:25	ClientAPI	Loaded ClientAPI mixin configuration
14:35:25	mixin	Mixin config mixins.client.json does not specify "minVersion" property
14:35:25	ClientAPI	Loaded Client mixin configuration
14:35:25	LaunchWrapper	Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
14:35:25	LaunchWrapper	Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
14:35:26	LaunchWrapper	Launching wrapped minecraft {net.minecraft.client.main.Main}
14:35:27	bib	Setting user: Lord_Quadrato
14:35:31	bib	LWJGL Version: 2.9.4
14:35:31	cev	Reloading ResourceManager: Default, f81517ca516363c381528480bb4c5189-New Default Betapack V2.zip
14:35:32	chm	Starting up SoundSystem...
14:35:32	chm	Initializing LWJGL OpenAL
14:35:32	chm	(The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
14:35:33	chm	OpenAL initialized.
14:35:33	chm	Sound engine started
14:35:37	cdp	Created: 1024x512 textures-atlas
14:35:39	com.mojang.text2speech.NarratorWindows	Narrator library for x64 successfully loaded
14:35:40	Impact	Loading Fonts
14:35:41	Impact	Loading Users
14:35:42	Impact	Initialized 106 mods!
14:35:42	Impact	Unable to load spam config file: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
14:35:43	bib	########## GL ERROR ##########
14:35:43	bib	@ Pre render
14:35:43	bib	1282: Invalid operation
14:36:15	bjb	[CHAT] Screenshot gespeichert unter 2018-04-24_14.36.15.png
14:36:29	bib	Reported exception thrown!
f: Updating screen events
	at bib.t(SourceFile:1635)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at me.zero.clarinet.bw.a(bw.java)
	at blk.a(SourceFile:337)
	at blk.k(SourceFile:400)
	at me.zero.clarinet.bw.k(bw.java)
	at blk.q(SourceFile:377)
	at bib.t(SourceFile:1625)
	... 9 more

--
```
### Crash report?
```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 4/24/18 2:37 PM
Description: Updating screen events

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at me.zero.clarinet.be.b(be.java)
	at blk.a(SourceFile:363)
	at bib.a(SourceFile:937)
	at me.zero.clarinet.bw.a(bw.java)
	at blk.a(SourceFile:337)
	at blk.k(SourceFile:400)
	at me.zero.clarinet.bw.k(bw.java)
	at blk.q(SourceFile:377)
	at bib.t(SourceFile:1625)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at me.zero.clarinet.be.b(be.java)
	at blk.a(SourceFile:363)
	at bib.a(SourceFile:937)
	at me.zero.clarinet.bw.a(bw.java)
	at blk.a(SourceFile:337)
	at blk.k(SourceFile:400)
	at me.zero.clarinet.bw.k(bw.java)
	at blk.q(SourceFile:377)

-- Affected screen --
Details:
	Screen name: me.zero.clarinet.be
Stacktrace:
	at bib.t(SourceFile:1625)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 234878912 bytes (223 MB) / 536870912 bytes (512 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.12.2-Impact_4.2
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 620 GL version 4.4.0 - Build 21.20.16.4534, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: f81517ca516363c381528480bb4c5189-New Default Betapack V2.zip
	Current Language: Deutsch (Deutschland)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
```

### Additional Client Info
- Impact Version: 4.2 for 1.12.2
- Using Optifine? No
- Enabled mods: Nothing (for testing purposes)
- Operating System: Windows 10 64bit

**Comment by LeafHacker** [comment]
Fixed in 4.3 by disabling the remove and edit buttons when the selected friend is out of range (i.e. no friend is selected).

Also gave the add/edit GUI a small polish: the alias is no longer treated like a password, the username doesn't get rendered as the alias, text box focusing makes a bit more sense, pressing Esc will go back to the main friends GUI.
