### ISSUE TITLE
Bug: Client crashes with Quakecraft module on Hypixel

### ISSUE THREAD

**Issue by LordQuadrato** [ImpactDevelopment/ImpactClient#566]
### What happens?
My client crashes while trying to play Quakecraft on Hypixel, when I join a game with the Quakecraft module enabled.

### Exact steps to reproduce?
1. Enable your Quakecraft mod
2. Join a Quakecraft game on Hypixel (hypixel.net)
`To join go to the Classic Games lobby and click the Quakecraft npc`
3. Wait until the game starts. **-> Your game will crash**

--------

<details> <summary><strong>Game output</strong></summary>

```
14:19:09	bjb	[CHAT] ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
14:19:09	bjb	[CHAT]                                 Quakecraft
14:19:09	bjb	[CHAT] 
14:19:09	bjb	[CHAT]             Right-click with your Railgun to shoot
14:19:09	bjb	[CHAT]                the enemy before they shoot you!
14:19:09	bjb	[CHAT]              Left-click with it to Dash and dodge!
14:19:09	bjb	[CHAT] 
14:19:09	bjb	[CHAT] ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
14:19:10	bib	Reported exception thrown!
f: Ticking entity
	at amu.k(SourceFile:1389)
	at bib.t(SourceFile:1691)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at me.zero.clarinet.a9.lambda$getEntities$5(a9.java)
	at me.zero.clarinet.a9$$Lambda$1225/1307214341.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at me.zero.clarinet.a9.a(a9.java)
	at me.zero.clarinet.bn.lambda$new$2(bn.java)
	at me.zero.clarinet.bn$$Lambda$367/1927507215.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.EventManager.lambda$post$5(EventManager.java:91)
	at me.zero.alpine.EventManager$$Lambda$1150/1003404175.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.EventManager.post(EventManager.java:91)
	at bud.N(SourceFile:1276)
	at bud.B_(SourceFile:206)
	at amu.a(SourceFile:1524)
	at amu.h(SourceFile:1500)
	at amu.k(SourceFile:1382)
	... 10 more

```

</details>

-------------------------------

<details> <summary><strong>Crash report</strong></summary>

```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 4/29/18 2:19 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at me.zero.clarinet.a9.lambda$getEntities$5(a9.java)
	at me.zero.clarinet.a9$$Lambda$1225/1307214341.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at me.zero.clarinet.a9.a(a9.java)
	at me.zero.clarinet.bn.lambda$new$2(bn.java)
	at me.zero.clarinet.bn$$Lambda$367/1927507215.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.EventManager.lambda$post$5(EventManager.java:91)
	at me.zero.alpine.EventManager$$Lambda$1150/1003404175.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.EventManager.post(EventManager.java:91)
	at bud.N(SourceFile:1276)
	at bud.B_(SourceFile:206)
	at amu.a(SourceFile:1524)
	at amu.h(SourceFile:1500)
	at amu.k(SourceFile:1382)
	at bib.t(SourceFile:1691)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at me.zero.clarinet.a9.lambda$getEntities$5(a9.java)
	at me.zero.clarinet.a9$$Lambda$1225/1307214341.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at me.zero.clarinet.a9.a(a9.java)
	at me.zero.clarinet.bn.lambda$new$2(bn.java)
	at me.zero.clarinet.bn$$Lambda$367/1927507215.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.EventManager.lambda$post$5(EventManager.java:91)
	at me.zero.alpine.EventManager$$Lambda$1150/1003404175.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.EventManager.post(EventManager.java:91)
	at bud.N(SourceFile:1276)
	at bud.B_(SourceFile:206)
	at amu.a(SourceFile:1524)
	at amu.h(SourceFile:1500)

-- Entity being ticked --
Details:
	Entity Type: null (me.zero.clarinet.hook.j)
	Entity ID: 17431
	Entity Name: Lord_Quadrato
	Entity's Exact location: -2379.50, 18.00, 705.50
	Entity's Block location: World: (-2380,18,705), Chunk: (at 4,1,1 in -149,44; contains blocks -2384,0,704 to -2369,255,719), Region: (-5,1; contains chunks -160,32 to -129,63, blocks -2560,0,512 to -2049,255,1023)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at amu.k(SourceFile:1382)

-- Affected level --
Details:
	Level name: MpServer
	All players: 3 total; [j['Lord_Quadrato'/17431, l='MpServer', x=-2379.50, y=18.00, z=705.50], bue['Zidoye'/41, l='MpServer', x=-2406.22, y=11.00, z=737.63], bue['tweets_'/44, l='MpServer', x=-2405.56, y=11.00, z=737.16]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-2388,21,743), Chunk: (at 12,1,7 in -150,46; contains blocks -2400,0,736 to -2385,255,751), Region: (-5,1; contains chunks -160,32 to -129,63, blocks -2560,0,512 to -2049,255,1023)
	Level time: 5469184 game time, 24000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 20 total; [j['Lord_Quadrato'/17431, l='MpServer', x=-2379.50, y=18.00, z=705.50], bue['Zidoye'/41, l='MpServer', x=-2406.25, y=11.00, z=737.63], bue['rubyy'/42, l='MpServer', x=-2406.50, y=11.00, z=738.00], bue['tweets_'/44, l='MpServer', x=-2405.53, y=11.00, z=737.13], bue['__CrazyNick__'/45, l='MpServer', x=-2423.61, y=11.58, z=765.40], bue['3D5isMyEgirl'/43, l='MpServer', x=-2410.14, y=18.42, z=759.11], bue['__CrazyNick__'/45, l='MpServer', x=-2441.80, y=16.33, z=748.76], bue['3D5isMyEgirl'/43, l='MpServer', x=-2437.02, y=12.05, z=755.70], bue['__CrazyNick__'/45, l='MpServer', x=-2413.09, y=26.00, z=745.47], bue['3D5isMyEgirl'/43, l='MpServer', x=-2436.09, y=22.50, z=765.16], bue['Zidoye'/41, l='MpServer', x=-2406.22, y=11.00, z=737.63], bue['rubyy'/42, l='MpServer', x=-2406.50, y=11.00, z=738.00], bue['3D5isMyEgirl'/43, l='MpServer', x=-2436.13, y=22.50, z=765.16], bue['tweets_'/44, l='MpServer', x=-2405.56, y=11.00, z=737.16], bue['__CrazyNick__'/45, l='MpServer', x=-2412.03, y=26.00, z=745.66], bue['Zidoye'/41, l='MpServer', x=-2406.22, y=11.00, z=737.63], bue['rubyy'/42, l='MpServer', x=-2406.50, y=11.00, z=738.00], bue['3D5isMyEgirl'/43, l='MpServer', x=-2436.13, y=22.50, z=765.16], bue['tweets_'/44, l='MpServer', x=-2405.56, y=11.00, z=737.16], bue['__CrazyNick__'/45, l='MpServer', x=-2412.03, y=26.00, z=745.66]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (Hypixel) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at bsb.a(SourceFile:366)
	at bib.b(SourceFile:2587)
	at bib.a(SourceFile:428)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 385175592 bytes (367 MB) / 905969664 bytes (864 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.12.2-Impact_4.2
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 620 GL version 4.4.0 - Build 21.20.16.4534, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
```

</details>

-------------------------------

<details> <summary><strong>Additional Client Info</strong></summary>
<br>

- Impact Version: 4.2 for 1.12.2
- Using Optifine? No
- Enabled mods: Quakecraft
- Operating System: Windows 10 64bit

</details>

**Comment by ZeroMemes** [comment]
Fixed in 4.4
