### ISSUE TITLE
Bug: Anti-Vanish error and game crash

### ISSUE THREAD

**Issue by LordQuadrato** [ImpactDevelopment/ImpactClient#573]
### What happens?
A few seconds after I activate Anti Vanish my client crashes.

### When does this happen?
Currently I only experienced this bug when activating Anti Vanish while in a game of Murder Mystery on Hypixel (not in the lobby). I'll update this issue if it happens on other servers too.

### Exact steps to reproduce?
I'll keep this issue up to date and find out when exactly this happens.

1. Join into a game of Murder Mystery on Hypixel (hypixel.net)
2. Activate Anti Vanish

**One of the following things happens:**
- You're game crashes
- You get kicked from the server (`Error message going to be added soon`)

<details>

<summary><strong>Game output</strong></summary>

```
13:26:12	bjb	[CHAT] Lord_Quadrato has joined (2/16)!
13:26:12	bjb	[CHAT] kwxl has joined (3/16)!
13:26:12	bjb	[CHAT] Search4Technik has joined (4/16)!
13:26:12	bjb	[CHAT] Gzchunhin has joined (5/16)!
13:26:12	bjb	[CHAT] Thirdy01 has joined (6/16)!
13:26:12	bjb	[CHAT] Pimmada has joined (7/16)!
13:26:19	bjb	[CHAT] EgorKarpt has joined (8/16)!
13:26:21	bjb	[CHAT] Egorkapopka has joined (9/16)!
13:26:22	bib	Unreported exception thrown!
java.lang.NullPointerException
	at bjc.a(SourceFile:31)
	at bjb.a(SourceFile:142)
	at bjb.a(SourceFile:132)
	at bjb.a(SourceFile:128)
	at me.zero.clarinet.T.b(T.java)
	at me.zero.clarinet.f3.lambda$null$3(f3.java)
	at me.zero.clarinet.f3$$Lambda$1270/685500307.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at me.zero.clarinet.f3.lambda$new$4(f3.java)
	at me.zero.clarinet.f3$$Lambda$905/639015907.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.EventManager.lambda$post$5(EventManager.java:91)
	at me.zero.alpine.EventManager$$Lambda$1153/2103485999.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.EventManager.post(EventManager.java:91)
	at bib.handler$preRunTick$zzm000(SourceFile:3181)
	at bib.t(SourceFile)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

</details>

<details>

<summary><strong>Crash report</strong></summary>

```
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 4/30/18 1:26 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at bjc.a(SourceFile:31)
	at bjb.a(SourceFile:142)
	at bjb.a(SourceFile:132)
	at bjb.a(SourceFile:128)
	at me.zero.clarinet.T.b(T.java)
	at me.zero.clarinet.f3.lambda$null$3(f3.java)
	at me.zero.clarinet.f3$$Lambda$1270/685500307.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at me.zero.clarinet.f3.lambda$new$4(f3.java)
	at me.zero.clarinet.f3$$Lambda$905/639015907.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.EventManager.lambda$post$5(EventManager.java:91)
	at me.zero.alpine.EventManager$$Lambda$1153/2103485999.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.EventManager.post(EventManager.java:91)
	at bib.handler$preRunTick$zzm000(SourceFile:3181)
	at bib.t(SourceFile)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at bjc.a(SourceFile:31)
	at bjb.a(SourceFile:142)
	at bjb.a(SourceFile:132)
	at bjb.a(SourceFile:128)
	at me.zero.clarinet.T.b(T.java)
	at me.zero.clarinet.f3.lambda$null$3(f3.java)
	at me.zero.clarinet.f3$$Lambda$1270/685500307.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at me.zero.clarinet.f3.lambda$new$4(f3.java)
	at me.zero.clarinet.f3$$Lambda$905/639015907.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.EventManager.lambda$post$5(EventManager.java:91)
	at me.zero.alpine.EventManager$$Lambda$1153/2103485999.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.EventManager.post(EventManager.java:91)
	at bib.handler$preRunTick$zzm000(SourceFile:3181)

-- Affected level --
Details:
	Level name: MpServer
	All players: 10 total; [j['Lord_Quadrato'/2813958, l='MpServer', x=49.25, y=53.00, z=-45.30], bue['Slime1480'/776, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['kwxl'/785, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['Search4Technik'/786, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['Gzchunhin'/787, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['Thirdy01'/788, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['Pimmada'/789, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['EgorKarpt'/790, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['Egorkapopka'/791, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['AnOriginalPanda'/793, l='MpServer', x=49.50, y=53.00, z=-46.50]]
	Chunk stats: MultiplayerChunkCache: 200, 200
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (382,64,-1282), Chunk: (at 14,4,14 in 23,-81; contains blocks 368,0,-1296 to 383,255,-1281), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
	Level time: 533744433 game time, 78000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 27 total; [bue['kwxl'/785, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['Search4Technik'/786, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['Gzchunhin'/787, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['Slime1480'/776, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['Thirdy01'/788, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['Pimmada'/789, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['EgorKarpt'/790, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['Egorkapopka'/791, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['AnOriginalPanda'/793, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['kwxl'/785, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['Search4Technik'/786, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['Gzchunhin'/787, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['Thirdy01'/788, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['Pimmada'/789, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['EgorKarpt'/790, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['Egorkapopka'/791, l='MpServer', x=49.50, y=53.00, z=-46.50], bue['AnOriginalPanda'/793, l='MpServer', x=49.50, y=53.00, z=-46.50], abz['Armor Stand'/41, l='MpServer', x=45.50, y=47.69, z=-28.00], acb['entity.ItemFrame.name'/42, l='MpServer', x=46.50, y=47.50, z=-27.97], acb['entity.ItemFrame.name'/43, l='MpServer', x=44.50, y=47.50, z=-27.97], afd['Boat'/45, l='MpServer', x=46.25, y=44.28, z=-7.75], abz['Armor Stand'/49, l='MpServer', x=-10.47, y=75.94, z=-44.50], abz['Armor Stand'/50, l='MpServer', x=-10.50, y=76.00, z=-44.50], abz['Armor Stand'/51, l='MpServer', x=-10.50, y=75.00, z=-39.50], abz['Armor Stand'/52, l='MpServer', x=-10.47, y=74.94, z=-39.50], j['Lord_Quadrato'/2813958, l='MpServer', x=49.25, y=53.00, z=-45.30], bue['Slime1480'/776, l='MpServer', x=49.50, y=53.00, z=-46.50]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (Hypixel) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at bsb.a(SourceFile:366)
	at bib.b(SourceFile:2587)
	at bib.a(SourceFile:433)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 454738616 bytes (433 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 1, tcache: 122, allocated: 13, tallocated: 95
	Launched Version: 1.12.2-Impact_4.2
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 620 GL version 4.4.0 - Build 21.20.16.4534, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
```

</details>

### Additional Client Info
- Impact Version: 4.2 for 1.12.2
- Using Optifine? No
- Enabled mods: Anti Vanish
- Operating System: Windows 10 64bit

**Comment by ZeroMemes** [comment]
Fixed in 4.4
