### ISSUE TITLE
.reconnect crashing client

### ISSUE THREAD

**Issue by WaffleTraits** [ImpactDevelopment/ImpactClient#649]
### What happens?
 Game crashes when you use .reconnect

### Exact steps to reproduce?

- Step one Get in game and type .reconnect

<details> 
  <summary><strong>Game output</strong></summary>
 

```
[17:02:55] [main/INFO]: Loading tweak class name clientapi.load.ClientTweaker
[17:02:55] [main/INFO]: Using primary tweak class name clientapi.load.ClientTweaker
[17:02:55] [main/INFO]: Calling tweak class clientapi.load.ClientTweaker
[17:02:55] [main/INFO]: Injecting into ClassLoader
[17:02:55] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.8 Source=file:/C:/Users/UserName/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.7.8-SNAPSHOT/mixin-0.7.8-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
[17:02:56] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[17:02:56] [main/INFO]: Initialized Mixin bootstrap
[17:02:56] [main/INFO]: Compatibility level set to JAVA_8
[17:02:56] [main/ERROR]: Mixin config mixins.capi.json does not specify "minVersion" property
[17:02:56] [main/INFO]: Loaded ClientAPI mixin configuration
[17:02:56] [main/ERROR]: Mixin config mixins.client.json does not specify "minVersion" property
[17:02:56] [main/INFO]: Loaded Client mixin configuration
[17:02:56] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[17:02:56] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[17:02:56] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[17:02:58] [main/INFO]: Setting user: xpielordx
[17:03:01] [main/INFO]: LWJGL Version: 2.9.4
[17:03:01] [main/INFO]: Reloading ResourceManager: Default
[17:03:02] [Sound Library Loader/INFO]: Starting up SoundSystem...
[17:03:02] [Thread-3/INFO]: Initializing LWJGL OpenAL
[17:03:02] [Thread-3/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[17:03:02] [Thread-3/ERROR]: Error in class 'LibraryLWJGLOpenAL'
[17:03:02] [Thread-3/ERROR]: Unable to initialize OpenAL.  Probable cause: OpenAL not supported.
[17:03:02] [Thread-3/WARN]: ERROR MESSAGE:
[17:03:02] [Thread-3/INFO]: Could not locate OpenAL library.
[17:03:02] [Thread-3/WARN]: STACK TRACE:
[17:03:02] [Thread-3/INFO]: org.lwjgl.openal.AL.create(AL.java:156)
[17:03:02] [Thread-3/INFO]: org.lwjgl.openal.AL.create(AL.java:102)
[17:03:02] [Thread-3/INFO]: org.lwjgl.openal.AL.create(AL.java:206)
[17:03:02] [Thread-3/INFO]: paulscode.sound.libraries.LibraryLWJGLOpenAL.init(LibraryLWJGLOpenAL.java:164)
[17:03:02] [Thread-3/INFO]: paulscode.sound.SoundSystem.CommandNewLibrary(SoundSystem.java:1576)
[17:03:02] [Thread-3/INFO]: paulscode.sound.SoundSystem.CommandQueue(SoundSystem.java:2572)
[17:03:02] [Thread-3/INFO]: paulscode.sound.CommandThread.run(CommandThread.java:121)
[17:03:02] [Sound Library Loader/WARN]: ERROR MESSAGE:
[17:03:02] [Sound Library Loader/INFO]: Could not locate OpenAL library.
[17:03:02] [Sound Library Loader/INFO]: Starting up SoundSystem...
[17:03:03] [Thread-5/INFO]: Switching to No Sound
[17:03:03] [Thread-5/INFO]: (Silent Mode)
[17:03:03] [Sound Library Loader/INFO]: Sound engine started
[17:03:06] [main/INFO]: Created: 1024x512 textures-atlas
[17:03:08] [main/INFO]: Narrator library for x64 successfully loaded
[17:03:10] [main/INFO]: Loading Fonts
[17:03:11] [main/INFO]: Checking for Updates
[17:03:11] [main/INFO]: Loading Users
[17:03:12] [main/INFO]: Initialized 108 mods!
[17:03:12] [main/FATAL]: Unable to load spam config file: Spam config file is in invalid format
[17:03:13] [main/ERROR]: ########## GL ERROR ##########
[17:03:13] [main/ERROR]: @ Pre render
[17:03:13] [main/ERROR]: 1282: Invalid operation
[17:11:38] [main/INFO]: Connecting to 8b8t.net, 25565
[17:11:41] [main/INFO]: [CHAT]                                      
[17:11:42] [main/INFO]: [CHAT] xpielordx joined the game
[17:11:42] [main/INFO]: Loaded 360 advancements
[17:14:35] [main/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: null
	at bky.handler$init$zdi000(SourceFile) ~[bky.class:?]
	at bky.<init>(SourceFile:20) ~[bky.class:?]
	at brz.a(SourceFile:689) ~[brz.class:?]
	at gw.l(SourceFile:381) ~[gw.class:?]
	at bsa.e(SourceFile:280) ~[bsa.class:?]
	at bib.t(SourceFile:1602) ~[bib.class:?]
	at bib.az(SourceFile:1000) ~[bib.class:?]
	at bib.a(SourceFile:419) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 7/16/18 5:14 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at bky.handler$init$zdi000(SourceFile)
	at bky.<init>(SourceFile:20)
	at brz.a(SourceFile:689)
	at gw.l(SourceFile:381)
	at bsa.e(SourceFile:280)
	at bib.t(SourceFile:1602)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 882940264 bytes (842 MB) / 1056964608 bytes (1008 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.12.2-Impact_4.3
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.36, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.3
- Using Optifine? No
- Enabled mods:  Anti Hunger, Middle Click Friend, Auto Reconnect, Criticals, RainbowEnchant, Chams, No Fall, Velocity, Radar, Velocity, Radar, Anti Overlay, Log Position, ItemPhysics, StorageESP, Anti Vanish, Camera Clip, Portal GUI, Animations, Nametags, Anti Blind, Tracers, ESP, No Push, Terrain, No Slow, Riding, Light
- Operating System:  Windows 10 64 bit

</details>
Also breadman shouldve fixed this, just making a post for the record.

**Comment by ZeroMemes** [comment]
Fixed in Impact 4.3 Hotfix 2
