### ISSUE TITLE
Impact 4.3 on Ubuntu 18.04 LTS 64 Bit crashes

### ISSUE THREAD

**Issue by Lvnvceo** [ImpactDevelopment/ImpactClient#663]
### What happens?

I recently switched over from windows 10 to Ubuntu. I am running Ubuntu 18.04 LTS 64 Bit. And when I try to run the game it shows a crash log and a game log output. I have installed impact 4.3 for 1.12.2. And when I try to boot the game it crashes.
### Exact steps to reproduce?

- Install Ubuntu 18.04 LTS 64 Bit
- Install minecraft from the ubuntu store
- Install Impact 4.3 into your versions folder.
- ERROR Game loads but not fully.

<details> 
  <summary><strong>Game output</strong></summary>
 

```
Picked up _JAVA_OPTIONS: -Dsun.java2d.xrender=true -Dprism.useFontConfig=false -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[18:22:45] [main/INFO]: Loading tweak class name clientapi.load.ClientTweaker
[18:22:45] [main/INFO]: Using primary tweak class name clientapi.load.ClientTweaker
[18:22:45] [main/INFO]: Calling tweak class clientapi.load.ClientTweaker
[18:22:45] [main/INFO]: Injecting into ClassLoader
[18:22:45] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.8 Source=file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/org/spongepowered/mixin/0.7.8-SNAPSHOT/mixin-0.7.8-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
[18:22:45] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[18:22:45] [main/INFO]: Initialized Mixin bootstrap
[18:22:45] [main/INFO]: Compatibility level set to JAVA_8
[18:22:45] [main/ERROR]: Mixin config mixins.capi.json does not specify "minVersion" property
[18:22:45] [main/INFO]: Loaded ClientAPI mixin configuration
[18:22:45] [main/ERROR]: Mixin config mixins.client.json does not specify "minVersion" property
[18:22:45] [main/INFO]: Loaded Client mixin configuration
[18:22:45] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[18:22:45] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[18:22:46] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[18:22:47] [main/INFO]: Setting user: DoctorWail
[18:22:49] [main/WARN]: Skipping bad option: lastServer:
[18:22:49] [main/INFO]: LWJGL Version: 2.9.4
[18:22:50] [main/INFO]: Reloading ResourceManager: Default
[18:22:50] [Sound Library Loader/INFO]: Starting up SoundSystem...
[18:22:50] [Thread-3/INFO]: Initializing LWJGL OpenAL
[18:22:50] [Thread-3/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[18:22:50] [Thread-3/INFO]: OpenAL initialized.
[18:22:51] [Sound Library Loader/INFO]: Sound engine started
[18:22:52] [main/INFO]: Created: 1024x512 textures-atlas
[18:22:53] [main/WARN]: ERROR : Couldn't load Narrator library : Unable to load library 'fliteWrapper': Native library (linux-x86-64/libfliteWrapper.so) not found in resource path ([file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/com/github/ImpactDevelopment/Impact/4.3-1.12.2/Impact-4.3-1.12.2.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/com/github/ImpactDevelopment/ClientAPI/3.0.2/ClientAPI-3.0.2.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/com/github/ZeroMemes/Alpine/1.6/Alpine-1.6.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/org/spongepowered/mixin/0.7.8-SNAPSHOT/mixin-0.7.8-SNAPSHOT.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/net/jodah/typetools/0.5.0/typetools-0.5.0.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar, file:/home/doctorwail/snap/minecraft/common/.minecraft/versions/1.12.2/1.12.2.jar])
[18:22:55] [main/INFO]: Loading Fonts
[18:22:55] [main/INFO]: Checking for Updates
[18:22:55] [main/INFO]: Loading Users
Gtk-Message: Failed to load module "canberra-gtk-module"
[18:22:56] [main/INFO]: Initialized 108 mods!
[18:22:57] [main/FATAL]: Unable to load spam config file: Spam config file is in invalid format
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 7/20/18 6:22 PM
Description: Initializing game

java.lang.ArrayIndexOutOfBoundsException: No such child: 0
	at java.awt.Container.getComponent(Container.java:334)
	at javax.swing.plaf.basic.CenterLayout.preferredLayoutSize(CenterLayout.java:42)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at javax.swing.JRootPane$RootLayout.preferredLayoutSize(JRootPane.java:920)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at java.awt.Window.pack(Window.java:809)
	at javax.swing.ColorChooserDialog.initColorChooserDialog(JColorChooser.java:716)
	at javax.swing.ColorChooserDialog.<init>(JColorChooser.java:626)
	at javax.swing.JColorChooser.createDialog(JColorChooser.java:179)
	at me.zero.clarinet.bk.<init>(bk.java)
	at me.zero.clarinet.bg.<init>(bg.java)
	at me.zero.clarinet.eM.a(eM.java)
	at me.zero.clarinet.eM.load(eM.java)
	at me.zero.clarinet.Impact.a(Impact.java)
	at me.zero.clarinet.Impact.onInit(Impact.java)
	at bib.handler$init$zzp000(SourceFile:3258)
	at bib.aq(SourceFile:583)
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.awt.Container.getComponent(Container.java:334)
	at javax.swing.plaf.basic.CenterLayout.preferredLayoutSize(CenterLayout.java:42)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at javax.swing.JRootPane$RootLayout.preferredLayoutSize(JRootPane.java:920)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at java.awt.Window.pack(Window.java:809)
	at javax.swing.ColorChooserDialog.initColorChooserDialog(JColorChooser.java:716)
	at javax.swing.ColorChooserDialog.<init>(JColorChooser.java:626)
	at javax.swing.JColorChooser.createDialog(JColorChooser.java:179)
	at me.zero.clarinet.bk.<init>(bk.java)
	at me.zero.clarinet.bg.<init>(bg.java)
	at me.zero.clarinet.eM.a(eM.java)
	at me.zero.clarinet.eM.load(eM.java)
	at me.zero.clarinet.Impact.a(Impact.java)
	at me.zero.clarinet.Impact.onInit(Impact.java)
	at bib.handler$init$zzp000(SourceFile:3258)
	at bib.aq(SourceFile:583)

-- Initialization --
Details:
Stacktrace:
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.0-29-generic
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 105356872 bytes (100 MB) / 290652160 bytes (277 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 5 total; -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.12.2-Impact_4.3
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.6.0 NVIDIA 390.48, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD Phenom(tm) II X6 1090T Processor
#@!@# Game crashed! Crash report saved to: #@!@# /home/doctorwail/snap/minecraft/common/.minecraft/crash-reports/crash-2018-07-20_18.22.57-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 7/20/18 6:22 PM
Description: Initializing game

java.lang.ArrayIndexOutOfBoundsException: No such child: 0
	at java.awt.Container.getComponent(Container.java:334)
	at javax.swing.plaf.basic.CenterLayout.preferredLayoutSize(CenterLayout.java:42)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at javax.swing.JRootPane$RootLayout.preferredLayoutSize(JRootPane.java:920)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at java.awt.Window.pack(Window.java:809)
	at javax.swing.ColorChooserDialog.initColorChooserDialog(JColorChooser.java:716)
	at javax.swing.ColorChooserDialog.<init>(JColorChooser.java:626)
	at javax.swing.JColorChooser.createDialog(JColorChooser.java:179)
	at me.zero.clarinet.bk.<init>(bk.java)
	at me.zero.clarinet.bg.<init>(bg.java)
	at me.zero.clarinet.eM.a(eM.java)
	at me.zero.clarinet.eM.load(eM.java)
	at me.zero.clarinet.Impact.a(Impact.java)
	at me.zero.clarinet.Impact.onInit(Impact.java)
	at bib.handler$init$zzp000(SourceFile:3258)
	at bib.aq(SourceFile:583)
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.awt.Container.getComponent(Container.java:334)
	at javax.swing.plaf.basic.CenterLayout.preferredLayoutSize(CenterLayout.java:42)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at javax.swing.JRootPane$RootLayout.preferredLayoutSize(JRootPane.java:920)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at java.awt.Window.pack(Window.java:809)
	at javax.swing.ColorChooserDialog.initColorChooserDialog(JColorChooser.java:716)
	at javax.swing.ColorChooserDialog.<init>(JColorChooser.java:626)
	at javax.swing.JColorChooser.createDialog(JColorChooser.java:179)
	at me.zero.clarinet.bk.<init>(bk.java)
	at me.zero.clarinet.bg.<init>(bg.java)
	at me.zero.clarinet.eM.a(eM.java)
	at me.zero.clarinet.eM.load(eM.java)
	at me.zero.clarinet.Impact.a(Impact.java)
	at me.zero.clarinet.Impact.onInit(Impact.java)
	at bib.handler$init$zzp000(SourceFile:3258)
	at bib.aq(SourceFile:583)

-- Initialization --
Details:
Stacktrace:
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.0-29-generic
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 105356872 bytes (100 MB) / 290652160 bytes (277 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 5 total; -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.12.2-Impact_4.3
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.6.0 NVIDIA 390.48, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD Phenom(tm) II X6 1090T Processor
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
4.3
- Using Optifine? 
No.
- Enabled mods: 
None.
- Operating System: 
Ubuntu 64Bit

</details>

**Comment by TheForgottenKing** [comment]
Cannot reproduce on same system version using the jar file, try doing that

**Comment by LeafHacker** [comment]
Hm, at first I suspected either you hadn't played 1.12.2 yet or you were using the wrong java version, but the crash report doesn't seem related to that. The java version is correct and it seems like the Minecraft classes are initially loaded ok.

It's possible this has nothing to do with your platform and is just a random crash that happens to affect you... :\

**Comment by Lvnvceo** [comment]
I keep getting it. The error and crash.

**Comment by Lvnvceo** [comment]
The minecraft regular version 1.12.2 works just fine with 100 or more FPS doing flawlessly. But when I try impact it crashes and gives me a crash report and game output. Also when I try other clients (I've tried JigSaw) it worked. But impact doesn't seem to be liking me.

**Comment by krusic22** [comment]
Tested on my old laptop using MultiMC worked fine. 
Just make sure you are using Java 8.

**Comment by TheForgottenKing** [comment]
Try deleting .minecraft and using the jar from minecraft.net

**Comment by LeafHacker** [comment]
@krusic22 @TheForgottenKing Please remember this isn't a forum to discuss potential workarounds, this is a place to identify and fix (in the code) the issue being tracked.

Also, please try to read the full thread before commenting; neither of your comments seem particularly relevant. I already said above that the log indicates he is using the correct Java version and I don't see how re-downloading Minecraft would help when vanilla Minecraft works fine for him, but Impact doesn't.

**Comment by Lvnvceo** [comment]
Good News. I got it fixed. I apparently installed minecraft from Ubuntu Store made by Snap. I reinstalled minecraft from the official website. No bug... My fault. Thank you for the help though.

**Comment by LeafHacker** [comment]
I wonder what's wrong with the Snap package, since it will be the same Minecraft stuff and it was running the right JRE... Odd, but at least you got it fixed
