### ISSUE TITLE
Impact 4.3 won't launch on Ubuntu 18.04-LTS

### ISSUE THREAD

**Issue by Husky2490** [ImpactDevelopment/ImpactClient#715]
### What happens?

Impact 4.3 won't launch. No game output is recorded, just the launcher output. Launcher says the game crashed
### Exact steps to reproduce?

- Install Debian version of Minecraft
- Run `minecraft-launcher`
- Download and launch Minecraft 1.12.2
- Close Minecraft and launcher
- Download Impact 4.3
- Run `cp ~/Download/'Impact 4.3 for Minecraft 1.12.2'/1.12.2-Impact_4.3 ~/.minecraft/versions`
- Run `minecraft-launcher`
- Create new launch profile using 1.12.2-Impact_4.3
- Launch 1.12.2-Impact_4.3
- Game doesn't launch and launcher says the game has crashed

<details> 
  <summary><strong>Launcher output</strong></summary>
 

```
[0923/211959:INFO:GameCallbacks.cpp(199)] launcher/launcher (main) debug Local file /home/husky2490/.minecraft/assets/objects/18/18e42d1640b500be08fba4e28529beb9d19a9fa6 has filesize of 11566 bytes
[0923/211959:INFO:GameCallbacks.cpp(199)] launcher/launcher (main) warn Couldn't get hash for org/spongepowered/mixin/0.7.8-SNAPSHOT/mixin-0.7.8-SNAPSHOT.jar from http://dl.liteloader.com/versions/org/spongepowered/mixin/0.7.8-SNAPSHOT/mixin-0.7.8-SNAPSHOT.jar.sha1: HTTP 404: Not Found
[0923/211959:INFO:GameCallbacks.cpp(199)] launcher/launcher (main) debug Got local file for mixin-0.7.8-SNAPSHOT.jar
[0923/211959:INFO:GameCallbacks.cpp(199)] launcher/launcher (main) debug Local file /home/husky2490/.minecraft/libraries/org/spongepowered/mixin/0.7.8-SNAPSHOT/mixin-0.7.8-SNAPSHOT.jar has filesize of 1007980 bytes
[0923/211959:INFO:GameCallbacks.cpp(199)] launcher/launcher (main) warn Have local file /home/husky2490/.minecraft/libraries/org/spongepowered/mixin/0.7.8-SNAPSHOT/mixin-0.7.8-SNAPSHOT.jar but don't know what size or hash it should be. Have to assume it's good.
[0923/211959:INFO:GameCallbacks.cpp(199)] launcher/launcher (main) info Checking installations.
[0923/211959:INFO:GameCallbacks.cpp(199)] launcher/launcher (main) info Minecraft client 1.12.2-Impact_4.3 is ready to start.
[0923/211959:INFO:GameCallbacks.cpp(199)] launcher/launcher (main) info Starting!
[0923/211959:INFO:GameCallbacks.cpp(199)] launcher/launcher (main) debug Nothing to download!
[0923/211959:INFO:GameCallbacks.cpp(199)] launcher/launcher (main) debug Extracting 3 files!
[0923/211959:INFO:GameCallbacks.cpp(199)] launcher/launcher (main) info Using default game log configuration client-1.12.xml (outputs XML)
[0923/211959:INFO:GameCallbacks.cpp(199)] launcher/launcher (main) debug Installing versions!
[0923/211959:INFO:ClientStarter.cpp(626)] ${natives_directory} == "/tmp/835e-cf7f-c764-52d4"
[0923/211959:INFO:ClientStarter.cpp(626)] ${launcher_name} == "minecraft-launcher"
[0923/211959:INFO:ClientStarter.cpp(626)] ${launcher_version} == "2.1.1349"
[0923/211959:INFO:ClientStarter.cpp(626)] ${primary_jar} == "/home/husky2490/.minecraft/versions/1.12.2/1.12.2.jar"
[0923/211959:INFO:ClientStarter.cpp(626)] ${classpath} == "/home/husky2490/.minecraft/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar:/home/husky2490/.minecraft/libraries/com/github/ImpactDevelopment/Impact/4.3-1.12.2/Impact-4.3-1.12.2.jar:/home/husky2490/.minecraft/libraries/com/github/ImpactDevelopment/ClientAPI/3.0.2/ClientAPI-3.0.2.jar:/home/husky2490/.minecraft/libraries/com/github/ZeroMemes/Alpine/1.6/Alpine-1.6.jar:/home/husky2490/.minecraft/libraries/org/spongepowered/mixin/0.7.8-SNAPSHOT/mixin-0.7.8-SNAPSHOT.jar:/home/husky2490/.minecraft/libraries/net/jodah/typetools/0.5.0/typetools-0.5.0.jar:/home/husky2490/.minecraft/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar:/home/husky2490/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar:/home/husky2490/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:/home/husky2490/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar:/home/husky2490/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:/home/husky2490/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar:/home/husky2490/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar:/home/husky2490/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar:/home/husky2490/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar:/home/husky2490/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar:/home/husky2490/.minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar:/home/husky2490/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar:/home/husky2490/.minecraft/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar:/home/husky2490/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar:/home/husky2490/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/home/husky2490/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar:/home/husky2490/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/home/husky2490/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/home/husky2490/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/home/husky2490/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:/home/husky2490/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar:/home/husky2490/.minecraft/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar:/home/husky2490/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:/home/husky2490/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:/home/husky2490/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/home/husky2490/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/home/husky2490/.minecraft/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar:/home/husky2490/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar:/home/husky2490/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar:/home/husky2490/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar:/home/husky2490/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar:/home/husky2490/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar:/home/husky2490/.minecraft/versions/1.12.2/1.12.2.jar"
[0923/211959:INFO:ClientStarter.cpp(626)] ${auth_player_name} == "husky2490"
[0923/211959:INFO:ClientStarter.cpp(626)] ${version_name} == "1.12.2-Impact_4.3"
[0923/211959:INFO:ClientStarter.cpp(626)] ${game_directory} == "/home/husky2490/.minecraft"
[0923/211959:INFO:ClientStarter.cpp(626)] ${assets_root} == "/home/husky2490/.minecraft/assets"
[0923/211959:INFO:ClientStarter.cpp(626)] ${assets_index_name} == "1.12"
[0923/211959:INFO:ClientStarter.cpp(626)] ${auth_uuid} == "29ba63512fa34ac2b4de6e9d498e0170"
[0923/211959:INFO:ClientStarter.cpp(626)] ${auth_access_token} == "724a7fef06604cae8277bc42ce160f89"
[0923/211959:INFO:ClientStarter.cpp(626)] ${user_type} == "mojang"
[0923/211959:INFO:LocalVersionProvider.cpp(82)] Looking for installed versions in /home/husky2490/.minecraft/versions
[0923/211959:INFO:ClientHandler.cpp(155)] Hiding launcher!
[0923/211959:WARNING:x11_util.cc(1404)] X error received: serial 170, error_code 3 (BadWindow (invalid Window parameter)), request_code 4, minor_code 0 (X_DestroyWindow)
[0923/211959:INFO:GameCallbacks.cpp(199)] launcher/launcher (main) info Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[0923/211959:INFO:GameCallbacks.cpp(199)] launcher/monitor (Process Monitor) fatal Process crashed with exit code 1
[0923/211959:INFO:GameCallbacks.cpp(31)] Destroying GameCallbacks!
[0923/211959:INFO:ClientHandler.cpp(182)] Creating launcher window.
[0923/211959:WARNING:mainLinux.cpp(25)] X error received: type 0, serial 2745, error_code 8, request_code 42, minor_code 0
[0923/211959:WARNING:x11_util.cc(1404)] X error received: serial 408, error_code 3 (BadWindow (invalid Window parameter)), request_code 4, minor_code 0 (X_DestroyWindow)
[0923/211959:INFO:LauncherAppRenderer.cpp(110)] Javascript bridge extended.
[0923/211959:INFO:ClientHandler.cpp(859)] Preferences / startup: Read preferences
[0923/211959:INFO:ClientHandler.cpp(859)] Preferences: Wrote preferences
[0923/211959:INFO:ClientHandler.cpp(859)] Configurations: Loading profiles
[0923/211959:INFO:ClientHandler.cpp(859)] Configuration d1e1da0f0400a57cab19bb6e73be464d: Wed Dec 31 1969 18:00:00 GMT-0600 (CST) < 2018-09-24T02:19:43.699Z
[0923/211959:INFO:ClientHandler.cpp(859)] Configuration a6e7fff6776e7a6b12e0dfc85578ed86: Sun Sep 23 2018 21:19:43 GMT-0500 (CDT) < 1970-01-01T00:00:00.000Z
[0923/211959:INFO:ClientHandler.cpp(859)] Configuration 04cbfbff1dca8523982c19b34394ce19: Sun Sep 23 2018 21:19:43 GMT-0500 (CDT) < 2018-09-24T02:19:11.874Z
[0923/211959:INFO:ClientHandler.cpp(859)] Configuration d801b898e7e7b98406472be1b352000d: Sun Sep 23 2018 21:19:43 GMT-0500 (CDT) < 2018-09-24T02:19:59.129Z
[0923/211959:INFO:ClientHandler.cpp(859)] Configurations: Loading settings
[0923/211959:INFO:ClientHandler.cpp(859)] Session: Read authDB
[0923/212000:INFO:LocalVersionProvider.cpp(82)] Looking for installed versions in /home/husky2490/.minecraft/versions
[0923/212000:INFO:ClientHandler.cpp(859)] Updating server status
[0923/212000:INFO:GameController.cpp(233)] Reinstancing game callbacks...
[0923/212000:INFO:ClientHandler.cpp(859)] GameStarter: Previous instance(s) found
[0923/212000:INFO:ClientHandler.cpp(859)] GameStarter: Previous instance crash detected
[0923/212000:INFO:ClientHandler.cpp(859)] Session: Validated token
[0923/212000:INFO:ClientHandler.cpp(859)] Preferences: Wrote preferences
[0923/212000:INFO:ClientHandler.cpp(859)] Session: Wrote authDB
[0923/212000:INFO:ClientHandler.cpp(859)] Changing view to: main.news
[0923/212327:WARNING:x11_util.cc(1404)] X error received: serial 4759, error_code 182 (GLXBadWindow), request_code 154, minor_code 26 (X_GLXMakeContextCurrent)
[0923/212327:INFO:ClientHandler.cpp(149)] Shutting down!
[0923/212327:WARNING:x11_util.cc(1404)] X error received: serial 198, error_code 3 (BadWindow (invalid Window parameter)), request_code 4, minor_code 0 (X_DestroyWindow)
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.3 for 1.12.2
- Using Optifine? No
- Enabled mods: None
- Operating System: Kubuntu 18.04-LTS

</details>

**Comment by Husky2490** [comment]
nvm, google helps

**Comment by Husky2490** [comment]
Fix:

1. Install `openjdk-8-jdk`
2. Get the java 8 jre location from `update-alternatives --list java`
3. Throw it into the Java Executable field of the profile (available after enabling advanced options)
