### ISSUE TITLE
Anti Vanish causes a ConcurrentModificationException

### ISSUE THREAD

**Issue by 9NONAGON** [ImpactDevelopment/ImpactClient#835]
Hello,

Every session I have on impact 4.4 ultimately ends with a sudden crash
the problem with this is that I can't reproduce it because I have no idea what causes it.
Like I said, it just happens randomly while doing anything. The crash report always reads "The game crashed because of an unexpected error"

The only 'lead' i have on this is that it only happens when Minecraft is the active window.
I understand if nothing can be done, but I appreciate anyone looking into it.

**Comment by VitorISs** [comment]
where's the crash log ?

**Comment by LeafHacker** [comment]
Use find/replace in any decent text editor (e.g. [notepad++][np] to remove any sensitive info? Or try and reproduce playing on a different server or in single player?

With logs and a crash report there's essentially no way to look into this.

**Comment by 9NONAGON** [comment]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 10/28/18 2:24 PM
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.ArrayList.forEach(ArrayList.java:1252)
	at me.zero.clarinet.bU.lambda$new$5(bU.java)
	at me.zero.clarinet.bU$$Lambda$1064/274474298.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$107/1178471274.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at clientapi.event.ClientAPIEventManager.post(ClientAPIEventManager.java:44)
	at bib.handler$preRunTick$zzp000(SourceFile:3174)
	at bib.t(SourceFile)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.forEach(ArrayList.java:1252)
	at me.zero.clarinet.bU.lambda$new$5(bU.java)
	at me.zero.clarinet.bU$$Lambda$1064/274474298.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$107/1178471274.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at clientapi.event.ClientAPIEventManager.post(ClientAPIEventManager.java:44)
	at bib.handler$preRunTick$zzp000(SourceFile:3174)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bud['NotTheAvgSteve'/4151, l='MpServer', x=]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to )
	Level time: 55167 game time, 1409781961 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 44 total; [zx['Cow'/13099207, l='MpServer', x=], zx['Cow'/13099206, l='MpServer', x=], zx['Cow'/13099205, l='MpServer', x=], zx['Cow'/13099204, l='MpServer', x=], zx['Cow'/13099203, l='MpServer', x=], zx['Cow'/13099202, l='MpServer', x=], zx['Cow'/13099201, l='MpServer', x=], zx['Cow'/13099200, l='MpServer', x=], adk['Skeleton'/13110208, l='MpServer', x=], zx['Cow'/13099211, l='MpServer', x=], zx['Cow'/13099210, l='MpServer', x=], zx['Cow'/13099209, l='MpServer', x=], zx['Cow'/13099208, l='MpServer', x=], bud['NotTheAvgSteve'/4151, l='MpServer', x=], acl['item.tile.woolCarpet.lime'/13104988, l='MpServer', x=], acl['item.tile.woolCarpet.lightBlue'/13133162, l='MpServer', x=], acl['item.tile.woolCarpet.lime'/13132524, l='MpServer', x=], zx['Cow'/13086319, l='MpServer', x=], zx['Cow'/13086318, l='MpServer', x=], acl['item.tile.hellrock'/13136226, l='MpServer', x=], zx['Cow'/13086316, l='MpServer', x=], zx['Cow'/13086315, l='MpServer', x=], acl['item.tile.woolCarpet.lightBlue'/13115769, l='MpServer', x=], acl['item.tile.woolCarpet.lime'/13133945, l='MpServer', x=], acl['item.tile.woolCarpet.lightBlue'/13133949, l='MpServer', x=], acl['item.tile.woolCarpet.lime'/13111024, l='MpServer', x=], aak['Iron Golem'/13101316, l='MpServer', x=], aak['Iron Golem'/13101315, l='MpServer', x=], aak['Iron Golem'/13101314, l='MpServer', x=], aak['Iron Golem'/13101313, l='MpServer', x=], afj['Minecart with Hopper'/13101953, l='MpServer', x=], aak['Iron Golem'/13101312, l='MpServer', x=], acl['item.tile.woolCarpet.lightBlue'/13101965, l='MpServer', x=3], acl['item.tile.woolCarpet.lime'/13101960, l='MpServer', x=], acl['item.tile.woolCarpet.lightBlue'/13101975, l='MpServer', x=], aau['Skeleton Horse'/13101339, l='MpServer', x=], afj['Minecart with Hopper'/13101338, l='MpServer', x=], adk['Skeleton'/13154728, l='MpServer', x=], acl['item.tile.woolCarpet.lime'/13123247, l='MpServer', x=], adk['Skeleton'/13135791, l='MpServer', x=], zx['Cow'/13099199, l='MpServer', x=], adk['Skeleton'/13135793, l='MpServer', x=], ady['Pete'/13099195, l='MpServer', x=], acl['item.tile.woolCarpet.lightBlue'/13129141, l='MpServer', x=]]
	Retry entities: 0 total; []
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.12-SNAPSHOT:4330d86:184) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at bsb.a(SourceFile:366)
	at bib.b(SourceFile:2587)
	at bib.a(SourceFile:433)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 321195256 bytes (306 MB) / 704643072 bytes (672 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 23, allocated: 13, tallocated: 95
	Launched Version: 1.12.2-Impact_4.4
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics Family GL version 3.1.0 - Build 8.15.10.2476, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz
