### ISSUE TITLE
Impact Issue When Launching MC

### ISSUE THREAD

**Issue by JTWood28** [ImpactDevelopment/ImpactClient#860]
- Version: Impact 4.4 MC 1.12.2
- Operating system: Windows 10, and if you meant MC, I use Java.
- Using Optifine? No.
- Using Liteloader? No.
- Active modules (if you manage to get into the menu): At the time when I left MC and then open later, I had Auto Sprint, Anti Vanish and X-Ray on.

When I open MC and look at the crash report it gives me this

>The game crashed whilst unexpected error
> Error: java.lang.NullPointerException: Unexpected error

<details> 
  <summary><strong>Crash report</strong></summary>

```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 11/8/18 5:57 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at me.zero.clarinet.d7.lambda$new$0(d7.java)
	at me.zero.clarinet.d7$$Lambda$767/845786722.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$107/292520508.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at clientapi.event.ClientAPIEventManager.post(ClientAPIEventManager.java:44)
	at bib.handler$preRunTick$zzp000(SourceFile:3174)
	at bib.t(SourceFile)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 85232360 bytes (81 MB) / 268435456 bytes (256 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.12.2-Impact_4.4
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 620 GL version 4.4.0 - Build 21.20.16.4550, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
```
</details>

If you need to contact me, my discord is JTWood#6303.

**Comment by ZeroMemes** [comment]
Fixed in 4.5. For now, ensure **Auto Clicker** is disabled through your config file by setting ``state`` to ``false``.

The config file is located in ``%appdata%/.minecraft/Impact/config/default.json``, or wherever your game install directory is located.

![Image](https://i.imgur.com/9XxSL07.png)

**Comment by LeafHacker** [comment]
It's at `.minecraft/Impact`. On Windows thats `%APPDATA%\.minecraft\Impact`.

**Comment by JTWood28** [comment]
Found it! Thanks for all the help! Can't wait to use Impact again!
