### ISSUE TITLE
Auto Walk module crashes after restart

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#916]
1. Enable Auto Walk
2. Restart the client fully, and note that Auto Walk is still shown as enabled even though it isn't doing anything
3. `.b goto ender_chest` or `.goto coords` or any Baritone command that isn't Auto Walk itself
4. The game will crash on arrival at your goal, with this stack trace:

```
java.lang.NullPointerException: Unexpected error
    at me.zero.clarinet.dP.r(dP.java)
    at me.zero.clarinet.dP.onPathEvent(dP.java)
    at baritone.y.a(Unknown Source)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at baritone.y.onPathEvent(Unknown Source)
    at baritone.l.b(Unknown Source)
    at baritone.l.onTick(Unknown Source)
    at baritone.y.a(Unknown Source)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at baritone.y.onTick(Unknown Source)
    at bib.handler$runTick$zef000(SourceFile)
    at bib.t(SourceFile:1623)
    at bib.az(SourceFile:1000)
    at bib.a(SourceFile:419)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

This is because Auto Walk is enabled, but has no direction or goal, so when it receives the AT_GOAL PathEvent from Baritone, it crashes while trying to extend the goal further in the same direction, since it's null.

Should still be an issue even with processes?

**Comment by leijurv** [comment]
Fixed in 4.5
