### ISSUE TITLE
Copy-Pasting in Macro makes the game to crash

### ISSUE THREAD

**Issue by weggethegamer** [ImpactDevelopment/ImpactClient#968]
### What happens?
OK so when i tried to copy paste a .goto command into macros the game crashed. 
### Exact steps to reproduce?
1. esc 
2. press impact button
3. Macros
4. Add
5. Copy paste.
6 Crashes

```
The game crashed whilst updating screen events
The game crashed whilst updating screen events
Error: java.lang.ArrayIndexOutOfBoundsException: -1
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// Oops.

Time: 2/27/19 9:31 PM
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at me.zero.clarinet.an.t(an.java:6)
	at me.zero.clarinet.an.b(an.java:24)
	at me.zero.clarinet.he.a(he.java:12)
	at blk.l(SourceFile:416)
	at blk.q(SourceFile:383)
	at bib.t(SourceFile:1625)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at me.zero.clarinet.an.t(an.java:6)
	at me.zero.clarinet.an.b(an.java:24)
	at me.zero.clarinet.he.a(he.java:12)
	at blk.l(SourceFile:416)
	at blk.q(SourceFile:383)

-- Affected screen --
Details:
	Screen name: me.zero.clarinet.he
Stacktrace:
	at bib.t(SourceFile:1625)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 165332016 bytes (157 MB) / 402653184 bytes (384 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.12.2-Impact_4.5
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 630 GL version 4.5.0 - Build 23.20.16.4973, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: &3Breeze.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.5
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods:Works in main menu
- Operating System: Windows 10 64bit

</details>

**Comment by ZeroMemes** [comment]
Fixed in 4.5 Hotfix 4
